/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jPack_ControlDeVentas;

/**
 *
 * @author Isabel
 */
public class jFrame_ControlDeVentas extends javax.swing.JFrame {
   //declarando variables como global
   double igv;
   double descuento;
   
    /**
     * Creates new form jFrame_ControlDeVentas
     */
    public jFrame_ControlDeVentas() {
        initComponents();
        //inicializar variables globales
        //se inicializa por que algunos productos no tienen igv o descuento
        igv=0;
        descuento=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo_Configuracion = new javax.swing.JDialog();
        label_titulo = new javax.swing.JLabel();
        label_igv = new javax.swing.JLabel();
        text_igv = new javax.swing.JTextField();
        label_descuento = new javax.swing.JLabel();
        text_descuento = new javax.swing.JTextField();
        boton_aceptar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_unidades = new javax.swing.JLabel();
        tex_precio = new javax.swing.JTextField();
        label_precio = new javax.swing.JLabel();
        text_unidades1 = new javax.swing.JTextField();
        label_total = new javax.swing.JLabel();
        label_total1 = new javax.swing.JLabel();
        boton_calcular = new javax.swing.JButton();
        boton_configurar = new javax.swing.JButton();

        dialogo_Configuracion.setAlwaysOnTop(true);
        dialogo_Configuracion.setModal(true);

        label_titulo.setText("Configurar  IGV-DESCUENTO");

        label_igv.setText("IGV(%): ");

        label_descuento.setText("Descuento(%):");

        boton_aceptar.setText("Aceptar");
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        boton_cancelar.setText("Cancelar");
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogo_ConfiguracionLayout = new javax.swing.GroupLayout(dialogo_Configuracion.getContentPane());
        dialogo_Configuracion.getContentPane().setLayout(dialogo_ConfiguracionLayout);
        dialogo_ConfiguracionLayout.setHorizontalGroup(
            dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_ConfiguracionLayout.createSequentialGroup()
                .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogo_ConfiguracionLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(label_titulo))
                    .addGroup(dialogo_ConfiguracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_descuento)
                            .addComponent(label_igv))
                        .addGap(18, 18, 18)
                        .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_descuento, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(text_igv))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dialogo_ConfiguracionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(boton_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(boton_cancelar)
                .addGap(43, 43, 43))
        );
        dialogo_ConfiguracionLayout.setVerticalGroup(
            dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_igv)
                    .addComponent(text_igv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descuento)
                    .addComponent(text_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(dialogo_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_aceptar)
                    .addComponent(boton_cancelar))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times", 2, 18)); // NOI18N
        jLabel1.setText("Contol Ventas(Dialogos)");

        label_unidades.setText("Unidades");

        label_precio.setText("Precio");

        label_total.setText("Total");

        label_total1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));

        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        boton_configurar.setText("Configurar...");
        boton_configurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_configurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_precio)
                            .addComponent(label_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_total))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tex_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_unidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(label_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_calcular)
                        .addGap(64, 64, 64)
                        .addComponent(boton_configurar)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_unidades)
                    .addComponent(text_unidades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_precio)
                    .addComponent(tex_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_total)
                    .addComponent(label_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_calcular)
                    .addComponent(boton_configurar))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
     double unidades;
     double precio;
     double total;
     double cantidadigv;
     double cantidaddescuento;
     double totalsinigv;
     //ingresar informacion del usuario
     unidades=Double.parseDouble(text_unidades1.getText());
     precio=Double.parseDouble(tex_precio.getText());
     //calcular el total sin igv
    totalsinigv=precio*unidades;
    cantidadigv=totalsinigv*igv/100;
    cantidaddescuento=totalsinigv*descuento/100;
    //calcular el total de pagar 
    total=totalsinigv+cantidadigv-cantidaddescuento;
    label_total1.setText("$/."+total);
    }//GEN-LAST:event_boton_calcularActionPerformed

    private void boton_configurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_configurarActionPerformed
     dialogo_Configuracion.setSize(300,250);
     dialogo_Configuracion.setLocation(100,100);
     dialogo_Configuracion.setVisible(true);
     
    }//GEN-LAST:event_boton_configurarActionPerformed

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
     //recuperar valores ingresados para el usuario
        igv=Double.parseDouble(text_igv.getText());
        descuento=Double.parseDouble(text_descuento.getText());
        dialogo_Configuracion.dispose();
        
        
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
     dialogo_Configuracion.dispose();
     //dispose para cerrar
    }//GEN-LAST:event_boton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_ControlDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_ControlDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_ControlDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_ControlDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_ControlDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JButton boton_calcular;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_configurar;
    private javax.swing.JDialog dialogo_Configuracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_descuento;
    private javax.swing.JLabel label_igv;
    private javax.swing.JLabel label_precio;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total1;
    private javax.swing.JLabel label_unidades;
    private javax.swing.JTextField tex_precio;
    private javax.swing.JTextField text_descuento;
    private javax.swing.JTextField text_igv;
    private javax.swing.JTextField text_unidades1;
    // End of variables declaration//GEN-END:variables
}
