
package jPack_botones_MarcoRath;

import javax.swing.JOptionPane;

public class jFrame_botones_MarcoRath extends javax.swing.JFrame {
   Clase_Pulsaciones_MarcoRath tocar = new Clase_Pulsaciones_MarcoRath();
    private int contadorA = 0;
    private int contadorB = 0;
   
    
    public jFrame_botones_MarcoRath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_b = new javax.swing.JButton();
        jbton_a = new javax.swing.JButton();
        jbtn_pulsaciones = new javax.swing.JButton();
        jbtn_reiniciar = new javax.swing.JButton();
        jbtn_disminuir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_b.setText("Boton B");
        jbtn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_bActionPerformed(evt);
            }
        });

        jbton_a.setText("Boton A");
        jbton_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbton_aActionPerformed(evt);
            }
        });

        jbtn_pulsaciones.setText("Ver Pulsaciones");
        jbtn_pulsaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pulsacionesActionPerformed(evt);
            }
        });

        jbtn_reiniciar.setText("Reiniciar");
        jbtn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_reiniciarActionPerformed(evt);
            }
        });

        jbtn_disminuir.setText("disminuir");
        jbtn_disminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_disminuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jbtn_pulsaciones)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_reiniciar)
                    .addComponent(jbtn_b))
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_disminuir)
                .addGap(192, 192, 192))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jbton_a)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jbtn_b)
                .addGap(39, 39, 39)
                .addComponent(jbtn_disminuir)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_pulsaciones)
                    .addComponent(jbtn_reiniciar))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jbton_a)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbton_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbton_aActionPerformed
         contadorA++;
        tocar.incrementar();
    }//GEN-LAST:event_jbton_aActionPerformed

    private void jbtn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_bActionPerformed
         contadorB++;
        tocar.incrementar();
    }//GEN-LAST:event_jbtn_bActionPerformed

    private void jbtn_pulsacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pulsacionesActionPerformed
    JOptionPane.showMessageDialog(this, "Pulsaciones Botón A: " + contadorA + "\nPulsaciones Botón B: " + contadorB +
                "\nPulsaciones Totales: " + tocar.getPulsaciones());
    }//GEN-LAST:event_jbtn_pulsacionesActionPerformed

    private void jbtn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_reiniciarActionPerformed
          contadorA = 0;
        contadorB = 0;
        tocar.reiniciar();
    }//GEN-LAST:event_jbtn_reiniciarActionPerformed

    private void jbtn_disminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_disminuirActionPerformed
       if (contadorA > 0) {
            contadorA--;
            tocar.decrementar();
        }
        if (contadorB > 0) {
            contadorB--;
            tocar.decrementar();
        }
    }//GEN-LAST:event_jbtn_disminuirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_botones_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_botones_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_botones_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_botones_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_botones_MarcoRath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_b;
    private javax.swing.JButton jbtn_disminuir;
    private javax.swing.JButton jbtn_pulsaciones;
    private javax.swing.JButton jbtn_reiniciar;
    private javax.swing.JButton jbton_a;
    // End of variables declaration//GEN-END:variables
}
