
import static java.lang.Compiler.enable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Isabel
 */
public class pregunta4 extends javax.swing.JFrame {

    /**
     * Creates new form pregunta4
     */
    public pregunta4() {
 
        initComponents();
    bar_1.setValue(5);
    bar_2.setValue(5);
    bar_3.setValue(5);
    bar_4.setValue(5);
    bar_5.setValue(5);  
    radio_plano.setSelected(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        bar_1 = new javax.swing.JScrollBar();
        bar_2 = new javax.swing.JScrollBar();
        bar_3 = new javax.swing.JScrollBar();
        bar_4 = new javax.swing.JScrollBar();
        bar_5 = new javax.swing.JScrollBar();
        label_1 = new javax.swing.JLabel();
        label_2 = new javax.swing.JLabel();
        label_3 = new javax.swing.JLabel();
        label_4 = new javax.swing.JLabel();
        label_5 = new javax.swing.JLabel();
        panel_ecualizacion = new javax.swing.JPanel();
        radio_pelicula = new javax.swing.JRadioButton();
        radio_concierto = new javax.swing.JRadioButton();
        radio_plano = new javax.swing.JRadioButton();
        check_1 = new javax.swing.JCheckBox();
        check_2 = new javax.swing.JCheckBox();
        check_3 = new javax.swing.JCheckBox();
        check_4 = new javax.swing.JCheckBox();
        check_5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bar_1.setMaximum(20);
        bar_1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                bar_1AdjustmentValueChanged(evt);
            }
        });

        bar_2.setMaximum(20);
        bar_2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                bar_2AdjustmentValueChanged(evt);
            }
        });

        bar_3.setMaximum(20);
        bar_3.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                bar_3AdjustmentValueChanged(evt);
            }
        });

        bar_4.setMaximum(20);
        bar_4.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                bar_4AdjustmentValueChanged(evt);
            }
        });

        bar_5.setMaximum(20);
        bar_5.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                bar_5AdjustmentValueChanged(evt);
            }
        });

        label_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        label_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        label_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        label_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        label_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        panel_ecualizacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ecualizaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        btngroup.add(radio_pelicula);
        radio_pelicula.setText("Pelicula");
        radio_pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_peliculaActionPerformed(evt);
            }
        });

        btngroup.add(radio_concierto);
        radio_concierto.setText("Concierto");
        radio_concierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_conciertoActionPerformed(evt);
            }
        });

        btngroup.add(radio_plano);
        radio_plano.setText("Plano");
        radio_plano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_planoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ecualizacionLayout = new javax.swing.GroupLayout(panel_ecualizacion);
        panel_ecualizacion.setLayout(panel_ecualizacionLayout);
        panel_ecualizacionLayout.setHorizontalGroup(
            panel_ecualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ecualizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ecualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_pelicula)
                    .addComponent(radio_concierto)
                    .addComponent(radio_plano))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panel_ecualizacionLayout.setVerticalGroup(
            panel_ecualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ecualizacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(radio_pelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_concierto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_plano)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        check_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_1ActionPerformed(evt);
            }
        });

        check_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_2ActionPerformed(evt);
            }
        });

        check_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_3ActionPerformed(evt);
            }
        });

        check_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_4ActionPerformed(evt);
            }
        });

        check_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bar_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bar_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bar_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bar_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bar_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)))
                .addComponent(panel_ecualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(check_1)
                .addGap(18, 18, 18)
                .addComponent(check_2)
                .addGap(18, 18, 18)
                .addComponent(check_3)
                .addGap(18, 18, 18)
                .addComponent(check_4)
                .addGap(18, 18, 18)
                .addComponent(check_5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_ecualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bar_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bar_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bar_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bar_1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(bar_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(check_1)
                        .addComponent(check_2)
                        .addComponent(check_3))
                    .addComponent(check_4)
                    .addComponent(check_5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bar_1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_bar_1AdjustmentValueChanged
       label_1.setText(""+bar_1.getValue());
    }//GEN-LAST:event_bar_1AdjustmentValueChanged

    private void bar_2AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_bar_2AdjustmentValueChanged
        label_2.setText("" + bar_2.getValue());
    }//GEN-LAST:event_bar_2AdjustmentValueChanged

    private void bar_3AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_bar_3AdjustmentValueChanged
         label_3.setText("" + bar_3.getValue());
    }//GEN-LAST:event_bar_3AdjustmentValueChanged

    private void bar_4AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_bar_4AdjustmentValueChanged
      label_4.setText("" + bar_4.getValue());
    }//GEN-LAST:event_bar_4AdjustmentValueChanged

    private void bar_5AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_bar_5AdjustmentValueChanged
        label_5.setText("" + bar_5.getValue());
    }//GEN-LAST:event_bar_5AdjustmentValueChanged

    private void check_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_1ActionPerformed
  if (check_1.isSelected()) {
        check_1.setEnabled(false);
        check_1.setEnabled(true);
        bar_1.setEnabled(false);
    } else {
        check_1.setEnabled(true);
        bar_1.setEnabled(true);
    }
    }//GEN-LAST:event_check_1ActionPerformed

    private void check_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_2ActionPerformed
        if (check_2.isSelected()) {
        check_2.setEnabled(false);
         check_2.setEnabled(true);
        bar_2.setEnabled(false);
    } else {
        check_2.setEnabled(true);
        bar_2.setEnabled(true);
    }
    }//GEN-LAST:event_check_2ActionPerformed

    private void check_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_3ActionPerformed
        if (check_3.isSelected()) {
        check_3.setEnabled(false);
         check_3.setEnabled(true);
        bar_3.setEnabled(false);
    } else {
        check_3.setEnabled(true);
        bar_3.setEnabled(true);
    }
    }//GEN-LAST:event_check_3ActionPerformed

    private void check_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_4ActionPerformed
        if (check_4.isSelected()) {
        check_4.setEnabled(false);
         check_4.setEnabled(true);
        bar_4.setEnabled(false);
    } else {
        check_4.setEnabled(true);
        bar_4.setEnabled(true);
    }
    }//GEN-LAST:event_check_4ActionPerformed

    private void check_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_5ActionPerformed
            if (check_5.isSelected()) {
        check_5.setEnabled(false);
         check_5.setEnabled(true);
        bar_5.setEnabled(false);
    } else {
        check_5.setEnabled(true);
        bar_5.setEnabled(true);
    }
    }//GEN-LAST:event_check_5ActionPerformed

    private void radio_peliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_peliculaActionPerformed
    bar_1.setValue(2);
    bar_2.setValue(5);
    bar_3.setValue(8);
    bar_4.setValue(5);
    bar_5.setValue(2);     
        
    }//GEN-LAST:event_radio_peliculaActionPerformed

    private void radio_conciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_conciertoActionPerformed
    bar_1.setValue(9);
    bar_2.setValue(5);
    bar_3.setValue(1);
    bar_4.setValue(5);
    bar_5.setValue(9);  
    }//GEN-LAST:event_radio_conciertoActionPerformed

    private void radio_planoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_planoActionPerformed
    bar_1.setValue(5);
    bar_2.setValue(5);
    bar_3.setValue(5);
    bar_4.setValue(5);
    bar_5.setValue(5);  
    }//GEN-LAST:event_radio_planoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pregunta4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar bar_1;
    private javax.swing.JScrollBar bar_2;
    private javax.swing.JScrollBar bar_3;
    private javax.swing.JScrollBar bar_4;
    private javax.swing.JScrollBar bar_5;
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JCheckBox check_1;
    private javax.swing.JCheckBox check_2;
    private javax.swing.JCheckBox check_3;
    private javax.swing.JCheckBox check_4;
    private javax.swing.JCheckBox check_5;
    private javax.swing.JLabel label_1;
    private javax.swing.JLabel label_2;
    private javax.swing.JLabel label_3;
    private javax.swing.JLabel label_4;
    private javax.swing.JLabel label_5;
    private javax.swing.JPanel panel_ecualizacion;
    private javax.swing.JRadioButton radio_concierto;
    private javax.swing.JRadioButton radio_pelicula;
    private javax.swing.JRadioButton radio_plano;
    // End of variables declaration//GEN-END:variables
}
