/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jPack_Menu;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabel
 */
public class jFrame_Menu extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_Menu
     */
    public jFrame_Menu() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poupmenu_prueba = new javax.swing.JPopupMenu();
        menuitem_ski = new javax.swing.JMenuItem();
        menuitem_morado = new javax.swing.JMenuItem();
        menuimte_naranja = new javax.swing.JMenuItem();
        tollbar_prueba = new javax.swing.JToolBar();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton_blue = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();
        menubar_prueba = new javax.swing.JMenuBar();
        menu1_archivo = new javax.swing.JMenu();
        menuitem_abir = new javax.swing.JMenuItem();
        separador_archivo = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuitem_salir = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        menu_principal = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        menuitem_ski.setText("Celeste\n");
        poupmenu_prueba.add(menuitem_ski);

        menuitem_morado.setText("Morado");
        poupmenu_prueba.add(menuitem_morado);

        menuimte_naranja.setText("Naranja");
        poupmenu_prueba.add(menuimte_naranja);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tollbar_prueba.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        tollbar_prueba.setRollover(true);
        tollbar_prueba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tollbar_pruebaMouseClicked(evt);
            }
        });

        boton1.setText("Uno");
        boton1.setFocusable(false);
        boton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tollbar_prueba.add(boton1);

        boton2.setText("Dos");
        boton2.setFocusable(false);
        boton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tollbar_prueba.add(boton2);

        boton3.setText("Tres");
        boton3.setFocusable(false);
        boton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tollbar_prueba.add(boton3);

        boton4.setText("Cuatro");
        boton4.setFocusable(false);
        boton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tollbar_prueba.add(boton4);

        boton_blue.setText("azul");
        boton_blue.setFocusable(false);
        boton_blue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_blue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_blueActionPerformed(evt);
            }
        });
        tollbar_prueba.add(boton_blue);

        getContentPane().add(tollbar_prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        label_resultado.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        label_resultado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        menu1_archivo.setText("Archivo");

        menuitem_abir.setText("Abrir");
        menuitem_abir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_abirActionPerformed(evt);
            }
        });
        menu1_archivo.add(menuitem_abir);
        menu1_archivo.add(separador_archivo);

        jMenuItem1.setText("Guardar");
        menu1_archivo.add(jMenuItem1);

        menuitem_salir.setText("Salir");
        menu1_archivo.add(menuitem_salir);

        menubar_prueba.add(menu1_archivo);

        editar.setText("Editar");

        menu_principal.setText("colores");

        jMenuItem2.setText("Rojo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_principal.add(jMenuItem2);

        jMenuItem3.setText("VERDE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_principal.add(jMenuItem3);

        jMenuItem4.setText("Amarillo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_principal.add(jMenuItem4);

        editar.add(menu_principal);

        menubar_prueba.add(editar);

        jMenu1.setText("Ayuda");
        menubar_prueba.add(jMenu1);

        jMenu2.setText("Salir");
        menubar_prueba.add(jMenu2);

        setJMenuBar(menubar_prueba);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_abirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_abirActionPerformed
     this.getContentPane().setBackground(Color.red);

    }//GEN-LAST:event_menuitem_abirActionPerformed

    private void boton_blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_blueActionPerformed
      this.getContentPane().setBackground(Color.blue);

    }//GEN-LAST:event_boton_blueActionPerformed

    private void tollbar_pruebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tollbar_pruebaMouseClicked
       
    }//GEN-LAST:event_tollbar_pruebaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        

  poupmenu_prueba.show(this,evt.getX(),getY());//si preciono el boton isquierdo
        
        if(evt.getButton()==1){
        JOptionPane.showMessageDialog(null, "Pulsaste el boton izquierdo");
       
        }
        else{
        if(evt.getButton()==2){
        
           JOptionPane.showMessageDialog(null, "Pulsaste el boton centro");
        }
        else{
        
        if(evt.getButton()==3){
           JOptionPane.showMessageDialog(null, "Pulsaste el boton derecho");
        
        }
        }
        
        }
    }//GEN-LAST:event_formMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         this.getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         this.getContentPane().setBackground(Color.yellow);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton_blue;
    private javax.swing.JMenu editar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JMenu menu1_archivo;
    private javax.swing.JMenu menu_principal;
    private javax.swing.JMenuBar menubar_prueba;
    private javax.swing.JMenuItem menuimte_naranja;
    private javax.swing.JMenuItem menuitem_abir;
    private javax.swing.JMenuItem menuitem_morado;
    private javax.swing.JMenuItem menuitem_salir;
    private javax.swing.JMenuItem menuitem_ski;
    private javax.swing.JPopupMenu poupmenu_prueba;
    private javax.swing.JPopupMenu.Separator separador_archivo;
    private javax.swing.JToolBar tollbar_prueba;
    // End of variables declaration//GEN-END:variables
}
