/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jPack_AbrirGuardar;

import javax.swing.JOptionPane;

/**
 *
 * @author Isabel
 */
public class jFrame_AbirGuardar extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_AbirGuardar
     */
    public jFrame_AbirGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser_abrir = new javax.swing.JFileChooser();
        chooser_guardar = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        salir_boton = new javax.swing.JButton();
        menu_abirguardar = new javax.swing.JMenuBar();
        menu_Archivo = new javax.swing.JMenu();
        item_abrir = new javax.swing.JMenuItem();
        item_guardar = new javax.swing.JMenuItem();
        menu_editar = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        salir_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/incon salir.PNG"))); // NOI18N
        salir_boton.setText("Salir");
        salir_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_botonActionPerformed(evt);
            }
        });

        menu_Archivo.setText("Archivos");
        menu_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ArchivoActionPerformed(evt);
            }
        });

        item_abrir.setText("Abrir");
        item_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_abrirActionPerformed(evt);
            }
        });
        menu_Archivo.add(item_abrir);

        item_guardar.setText("Guardar");
        item_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_guardarActionPerformed(evt);
            }
        });
        menu_Archivo.add(item_guardar);

        menu_abirguardar.add(menu_Archivo);

        menu_editar.setText("Editar");
        menu_abirguardar.add(menu_editar);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menu_abirguardar.add(salir);

        setJMenuBar(menu_abirguardar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(salir_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addComponent(salir_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_guardarActionPerformed

    private void item_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_abrirActionPerformed
    //declarar auxiliar de respuesta del fileChosser
        int aux; 
        //shoopenifile va abrir solo el archivo 
        aux=chooser_abrir.showOpenDialog(this);
        //approve _opption es para abrir
        if(aux==chooser_abrir.APPROVE_OPTION){
            //get obtener 
        JOptionPane.showMessageDialog(null, chooser_abrir.getSelectedFile().toString());
        }
        
        else{
            //cancel_option es para cancelar 
        if(aux==chooser_abrir.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "PRESIONASTE CANCELAR ......");
        }
        }
      
    }//GEN-LAST:event_item_abrirActionPerformed

    private void menu_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ArchivoActionPerformed
 int aux2; 
        //shoopenifile va abrir solo el archivo 
        aux2=chooser_guardar.showOpenDialog(this);
        //approve _opption es para abrir
        if(aux2==chooser_guardar.APPROVE_OPTION){
            //get obtener 
        JOptionPane.showMessageDialog(null, chooser_guardar.getSelectedFile().toString());
        }
        
        else{
            //cancel_option es para cancelar 
        if(aux2==chooser_abrir.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "PRESIONASTE CANCELAR ......");
        }
        }
       
    }//GEN-LAST:event_menu_ArchivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salir_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_botonActionPerformed
       this.dispose();
    }//GEN-LAST:event_salir_botonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
      dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_AbirGuardar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser_abrir;
    private javax.swing.JFileChooser chooser_guardar;
    private javax.swing.JMenuItem item_abrir;
    private javax.swing.JMenuItem item_guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu menu_Archivo;
    private javax.swing.JMenuBar menu_abirguardar;
    private javax.swing.JMenu menu_editar;
    private javax.swing.JMenu salir;
    private javax.swing.JButton salir_boton;
    // End of variables declaration//GEN-END:variables
}
