/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame_varios;

/**
 *
 * @author Isabel
 */
public class Jframe_Varios extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_Varios
     */
    public Jframe_Varios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        label_Siler = new javax.swing.JLabel();
        label_ValorSlider = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        Spinner_prueba = new javax.swing.JSpinner();
        valoresSlider_label = new javax.swing.JLabel();
        spider = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        scroll_prueba = new javax.swing.JScrollBar();
        label_scroll = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setText("Probando Componentes");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        label_Siler.setText("Slider");
        getContentPane().add(label_Siler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label_ValorSlider.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 0)));
        getContentPane().add(label_ValorSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 420, 40));

        jSlider1.setMaximum(500);
        jSlider1.setMinimum(100);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(400);
        jSlider1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 51)));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 410, 60));

        Spinner_prueba.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_pruebaStateChanged(evt);
            }
        });
        getContentPane().add(Spinner_prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 50, -1));

        valoresSlider_label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(valoresSlider_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 470, 40));

        spider.setText("Spider");
        getContentPane().add(spider, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel1.setText("Scroll _barl");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        scroll_prueba.setBlockIncrement(20);
        scroll_prueba.setMaximum(150);
        scroll_prueba.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scroll_prueba.setUnitIncrement(2);
        scroll_prueba.setVisibleAmount(5);
        scroll_prueba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        scroll_prueba.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scroll_pruebaAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(scroll_prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 470, -1));

        label_scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        getContentPane().add(label_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 390, 50));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
    label_ValorSlider.setText("El slider esta en .,.." + jSlider1.getValue());
    }//GEN-LAST:event_jSlider1StateChanged

    private void Spinner_pruebaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_pruebaStateChanged
      valoresSlider_label.setText("eL SPINNER ESTAN EN ..... " + Spinner_prueba.getValue().toString());
    }//GEN-LAST:event_Spinner_pruebaStateChanged

    private void scroll_pruebaAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scroll_pruebaAdjustmentValueChanged
     label_scroll.setText("El scroll bar esta en ....." + scroll_prueba.getValue());
     //set =enviar; get=optener

    }//GEN-LAST:event_scroll_pruebaAdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_Varios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_Varios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_Varios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_Varios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_Varios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinner_prueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label_Siler;
    private javax.swing.JLabel label_ValorSlider;
    private javax.swing.JLabel label_scroll;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JScrollBar scroll_prueba;
    private javax.swing.JLabel spider;
    private javax.swing.JLabel valoresSlider_label;
    // End of variables declaration//GEN-END:variables
}
