/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_Semaforo;

/**
 *
 * @author Isabel
 */
public class jFrame_Semaforos extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_Semaforos
     */
    public jFrame_Semaforos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_boton = new javax.swing.ButtonGroup();
        jPanel_Semaforo = new javax.swing.JPanel();
        label_Titulo = new javax.swing.JLabel();
        jPanel1_Semaforo = new javax.swing.JPanel();
        radioboton_rojo = new javax.swing.JRadioButton();
        radioboton_amarrillo = new javax.swing.JRadioButton();
        radioboton_verde = new javax.swing.JRadioButton();
        boton_aceptar = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Titulo.setText("Semaforo");

        jPanel1_Semaforo.setBorder(javax.swing.BorderFactory.createTitledBorder("Semaforo\n"));

        group_boton.add(radioboton_rojo);
        radioboton_rojo.setText("Rojo");

        group_boton.add(radioboton_amarrillo);
        radioboton_amarrillo.setText("Amarrillo");

        group_boton.add(radioboton_verde);
        radioboton_verde.setText("Verde");

        javax.swing.GroupLayout jPanel1_SemaforoLayout = new javax.swing.GroupLayout(jPanel1_Semaforo);
        jPanel1_Semaforo.setLayout(jPanel1_SemaforoLayout);
        jPanel1_SemaforoLayout.setHorizontalGroup(
            jPanel1_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_SemaforoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioboton_rojo)
                    .addComponent(radioboton_amarrillo)
                    .addComponent(radioboton_verde))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1_SemaforoLayout.setVerticalGroup(
            jPanel1_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_SemaforoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioboton_rojo)
                .addGap(18, 18, 18)
                .addComponent(radioboton_amarrillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(radioboton_verde))
        );

        boton_aceptar.setText("aceptar");
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SemaforoLayout = new javax.swing.GroupLayout(jPanel_Semaforo);
        jPanel_Semaforo.setLayout(jPanel_SemaforoLayout);
        jPanel_SemaforoLayout.setHorizontalGroup(
            jPanel_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SemaforoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1_Semaforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Titulo))
                    .addGroup(jPanel_SemaforoLayout.createSequentialGroup()
                        .addComponent(boton_aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(salir))
                    .addGroup(jPanel_SemaforoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_SemaforoLayout.setVerticalGroup(
            jPanel_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SemaforoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Titulo)
                .addGap(59, 59, 59)
                .addComponent(jPanel1_Semaforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_SemaforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_aceptar)
                    .addComponent(salir))
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Semaforo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Semaforo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
    
    //creando la variable mensaje     
    String mensaje="El semaforo esta en : ";
    //condicion para seleccionar
    if(radioboton_rojo.isSelected()){
        mensaje=mensaje + "Rojo ";
    }
    else if(radioboton_amarrillo.isSelected()){
        mensaje=mensaje + "Amarrillo";
    }
     else if(radioboton_verde.isSelected()){
        mensaje=mensaje + "Verde ";
    }
      //mensaje final o en la pantallla
    resultado.setText(mensaje);
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
      this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Semaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Semaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Semaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Semaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Semaforos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.ButtonGroup group_boton;
    private javax.swing.JPanel jPanel1_Semaforo;
    private javax.swing.JPanel jPanel_Semaforo;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JRadioButton radioboton_amarrillo;
    private javax.swing.JRadioButton radioboton_rojo;
    private javax.swing.JRadioButton radioboton_verde;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
