/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jPack_garage;

/**
 *
 * @author Isabel
 */
public class jFrame_Garage extends javax.swing.JFrame {
    //declarar coches como variable global
    int coches;
    /**
     * Creates new form jFrame_Garage
     */
    public jFrame_Garage() {  
        initComponents();
        //contador 
    coches=0; 
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_garage = new javax.swing.JLabel();
        boton_ingresacoche = new javax.swing.JButton();
        boton_salircoche = new javax.swing.JButton();
        boton_nuevodia = new javax.swing.JButton();
        label_numerocochesgarage = new javax.swing.JLabel();
        label_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_garage.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        label_garage.setText("Garage \"El Marcelio De Los Conos \"");

        boton_ingresacoche.setText("Ingrese un Coche:");
        boton_ingresacoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ingresacocheMouseClicked(evt);
            }
        });
        boton_ingresacoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ingresacocheActionPerformed(evt);
            }
        });

        boton_salircoche.setText("Sale Un Coche:");
        boton_salircoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salircocheActionPerformed(evt);
            }
        });

        boton_nuevodia.setText("Nuevo Dia :");
        boton_nuevodia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevodiaActionPerformed(evt);
            }
        });

        label_numerocochesgarage.setText("Coches en el Garage : ");

        label_resultado.setFont(new java.awt.Font("Times", 2, 14)); // NOI18N
        label_resultado.setForeground(new java.awt.Color(0, 51, 51));
        label_resultado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(label_garage, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_salircoche)
                            .addComponent(boton_ingresacoche)
                            .addComponent(boton_nuevodia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label_numerocochesgarage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_garage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(boton_ingresacoche)
                .addGap(30, 30, 30)
                .addComponent(boton_salircoche)
                .addGap(34, 34, 34)
                .addComponent(boton_nuevodia)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numerocochesgarage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ingresacocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingresacocheMouseClicked
  
    }//GEN-LAST:event_boton_ingresacocheMouseClicked

    private void boton_ingresacocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ingresacocheActionPerformed
     coches=coches + 1;
   
     label_resultado.setText("los coches son : "+ coches);
     
    }//GEN-LAST:event_boton_ingresacocheActionPerformed

    private void boton_salircocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salircocheActionPerformed

     coches=coches -1;
    
     label_resultado.setText("los coches son : "+ coches);     

    }//GEN-LAST:event_boton_salircocheActionPerformed

    private void boton_nuevodiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevodiaActionPerformed
        label_resultado.setText(null);
    }//GEN-LAST:event_boton_nuevodiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Garage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_ingresacoche;
    private javax.swing.JButton boton_nuevodia;
    private javax.swing.JButton boton_salircoche;
    private javax.swing.JLabel label_garage;
    private javax.swing.JLabel label_numerocochesgarage;
    private javax.swing.JLabel label_resultado;
    // End of variables declaration//GEN-END:variables
}
