/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPack_JhontanEspinoza;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class jFrame_MarDepart extends javax.swing.JInternalFrame {
    private Connection conexion;
    private Statement sentencia;
    private DefaultTableModel modeloTabla;
    public jFrame_MarDepart() {
        initComponents();
        PrepararBaseDatos();
    }
        public void PrepararBaseDatos(){
    //cargar el controlador 
       
    try{
     String Controlador="com.microsoft.sqlserver.jdbc.SQLServerDriver";
     Class.forName(Controlador).newInstance();
     JOptionPane.showMessageDialog(null," ***** Conectado ******");
    }
    catch(Exception e){
         JOptionPane.showMessageDialog(null,"*-*  Nose puede Conectar *-* ");
    }
   
    
    
     try{
     String DSN="jdbc:sqlserver://DESKTOP-SR2O0L0:1433;databaseName=VentaLibros_NombreAP;encrypt=false";
     String user="marco1";
     String password="123";
     conexion=DriverManager.getConnection(DSN,user,password);
      JOptionPane.showMessageDialog(null," **** BASE DE DATOS CONECTADOOO ***");
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR NOSE PUEDE CONECTAR");
    }
           try{
               
              sentencia=conexion.createStatement(
              ResultSet.TYPE_SCROLL_INSENSITIVE,
              ResultSet.CONCUR_READ_ONLY);
             
           JOptionPane.showMessageDialog(null," **** CREA EL OBJETO DE SENTENCIA***");
           }
          catch(Exception e){
                   JOptionPane.showMessageDialog(null," **** ERROR AL CREAR OBJETO SENTENCIA ***"); 
          }
    
    }
    
   
    private void cargarDatos() {
        try {
            String[] etiquetas = { "Identificador", "Nombre" };
            modeloTabla = new DefaultTableModel(null, etiquetas);
            
            ResultSet resultado;
            resultado = sentencia.executeQuery("SELECT * FROM Departamento");
            
            while (resultado.next()) {
                String fila[] = new String[2];
                fila[0] = resultado.getString(1);
                fila[1] = resultado.getString(2);
                modeloTabla.addRow(fila);
            }
            
            jTable1_mantenimientoDepartamento.setModel(modeloTabla);
            
            JOptionPane.showMessageDialog(null, "Se cargaron los departamentos en la tabla");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al consultar la tabla Departamento");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jbtn_mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_mantenimientoDepartamento = new javax.swing.JTable();
        jlabel_idDepartamento = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jlabel_nombre = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbtn_Eliminar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();

        jLabel1_titulo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1_titulo.setText("MANTENIMIENTO DE DEPARTAMENTO");

        jbtn_nuevo.setText("Nuevo");

        jbtn_editar.setText("Editar");

        jbtn_mostrar.setText("Mostrar");
        jbtn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_mostrarActionPerformed(evt);
            }
        });

        jTable1_mantenimientoDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_mantenimientoDepartamento);

        jlabel_idDepartamento.setText("Identificador: ");

        jlabel_nombre.setText("Nombre: ");

        jbtn_Eliminar.setText("Eliminar");

        jbtn_actualizar.setText("Actualizar");

        jbtn_guardar.setText("Guardar");

        jbtn_cancelar.setText("Cancelar");

        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_Eliminar)
                                .addGap(21, 21, 21)
                                .addComponent(jbtn_actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_guardar)
                                .addGap(34, 34, 34)
                                .addComponent(jbtn_cancelar)
                                .addGap(33, 33, 33)
                                .addComponent(jbtn_salir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel_idDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_nuevo)
                                .addGap(37, 37, 37)
                                .addComponent(jbtn_editar)
                                .addGap(32, 32, 32)
                                .addComponent(jbtn_mostrar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_titulo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_nuevo)
                    .addComponent(jbtn_editar)
                    .addComponent(jbtn_mostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel_idDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel_nombre)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Eliminar)
                    .addComponent(jbtn_actualizar)
                    .addComponent(jbtn_guardar)
                    .addComponent(jbtn_cancelar)
                    .addComponent(jbtn_salir))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_mostrarActionPerformed
          try {
        String etiquetas[] = { "Identificador", "Nombre" };
        DefaultTableModel modeloTabla = new DefaultTableModel(null, etiquetas);
        
        ResultSet resultado;
        resultado = sentencia.executeQuery("SELECT * FROM Departamento");
        
        while (resultado.next()) {
            String fila[] = new String[2];
            fila[0] = resultado.getString(1);
            fila[1] = resultado.getString(2);
            modeloTabla.addRow(fila);
        }
        
        jTable1_mantenimientoDepartamento.setModel(modeloTabla);
        
        JOptionPane.showMessageDialog(null, "Se cargaron los departamentos en la tabla");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al consultar la tabla Departamento");
    }
    }//GEN-LAST:event_jbtn_mostrarActionPerformed

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
    this.dispose();
    }//GEN-LAST:event_jbtn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_mantenimientoDepartamento;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtn_Eliminar;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_editar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JButton jbtn_mostrar;
    private javax.swing.JButton jbtn_nuevo;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JLabel jlabel_idDepartamento;
    private javax.swing.JLabel jlabel_nombre;
    // End of variables declaration//GEN-END:variables
}
