
package JPack_DisneyLandPark_MarcoAntonioRathChipani;

public class JFrame_DisneyLandPark_MarcoRath extends javax.swing.JFrame {

   //creando los obejetos 
    JClase_DisneyLandPark carrusel;
    JClase_DisneyLandPark carruselCarritoChocante;
    JClase_DisneyLandPark carruselMontaniaRusa;
    
    public JFrame_DisneyLandPark_MarcoRath() {
        initComponents();
        //centrar
        setLocationRelativeTo(null);
        
        // contruimos los objetos
        carrusel = new JClase_DisneyLandPark();
        carruselCarritoChocante = new JClase_DisneyLandPark();
        carruselMontaniaRusa = new JClase_DisneyLandPark();
        //asignar valores segun el juego mecanico
        //valores para carrusel
       
        carrusel.setCapacidad(15);
        carrusel.setEntrada(5.00);
        
       //valores para carritos chocantes
       carruselCarritoChocante.setCapacidad(8);
       carruselCarritoChocante.setEntrada(10.00);
       
        //valores para montaña rusa
       carruselMontaniaRusa.setCapacidad(20);
       carruselMontaniaRusa.setEntrada(10.00);
    }
    public void Estadistica(){
        double tIngresos = carrusel.getIngresos()+carruselMontaniaRusa.getIngresos()+carruselCarritoChocante.getIngresos();
        int tOcupadas = carrusel.ocupados +carruselCarritoChocante.ocupados + carruselMontaniaRusa.ocupados ;
        int tVacias = carrusel.getLibres()+carruselCarritoChocante.getLibres()+carruselMontaniaRusa.getLibres();
        
        jLabel_s_in.setText(Double.toString(tIngresos));
        jLabel_s_oc.setText(Integer.toString(tOcupadas));
        jLabel_s_va.setText(Integer.toString(tVacias));
        
       
    }
    public void Estadist_PSO(){
        double porT;
        double cap=43;
        porT = Math.round((double)(carrusel.ocupados+(double)carruselCarritoChocante.ocupados+(double)carruselMontaniaRusa.ocupados)/(double)cap*100);
        
        jLabel_s_pr.setText(Double.toString(porT));
    }
    public void Mas_recaudo(){
        if (carrusel.getIngresos()> carruselCarritoChocante.getIngresos() && carrusel.getIngresos()> carruselMontaniaRusa.getIngresos()){
            jLabel_masRecaudo.setText("CARRUSEL" + " (" +jCBox_Tipo_carrusel.getSelectedItem().toString() + " )");
        }else if(carruselCarritoChocante.getIngresos()> carrusel.getIngresos() && carruselCarritoChocante.getIngresos()> carruselMontaniaRusa.getIngresos()){
            jLabel_masRecaudo.setText("CARRITO CHOCONES" + " ("+ jCBox_Tipo_carritosChocones.getSelectedItem().toString()+ " )");
        }else if(carruselMontaniaRusa.getIngresos()> carrusel.getIngresos() && carruselMontaniaRusa.getIngresos()> carruselCarritoChocante.getIngresos()){
            jLabel_masRecaudo.setText("MONTAÑA RUSA" + " ("+ jCBox_Tipo_Montaña.getSelectedItem().toString()+ " )");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_carrusel_estadist = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_tipoCarrusel_D1 = new javax.swing.JLabel();
        jLabel_Ocupadas_porcentaje_D1 = new javax.swing.JLabel();
        jLabel_sillasOcupadas_D1 = new javax.swing.JLabel();
        jLabel_carrusel_ingresos_D1 = new javax.swing.JLabel();
        jLabel_sillasVacias_carrusel_D1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jDialog_carritosChocones = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel_tipoChocones_D1 = new javax.swing.JLabel();
        jLabel_OcupadasPor_chocones_D1 = new javax.swing.JLabel();
        jLabel_sillasOc_Chocones_D1 = new javax.swing.JLabel();
        jLabel_ingresos_chocones_D1 = new javax.swing.JLabel();
        jLabel_sillasVacias_chocones_D1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jDialog_MontaniaRusia = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel_tipoMontania_D1 = new javax.swing.JLabel();
        jLabel_OcupadasPor_Montania_D1 = new javax.swing.JLabel();
        jLabel_sillasOcu_Montania_D1 = new javax.swing.JLabel();
        jLabel_carrusel_ingre_Montania_D1 = new javax.swing.JLabel();
        jLabel_sillasVacias_Montania_D1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_carrusel = new javax.swing.JPanel();
        jLabel_tipOCarrusel = new javax.swing.JLabel();
        jCBox_Tipo_carrusel = new javax.swing.JComboBox<>();
        jBtn_carrusel_nuevaVenta = new javax.swing.JButton();
        jButn_carrusel_vaciar = new javax.swing.JButton();
        jBtn_carrusel_Ocupados = new javax.swing.JButton();
        jButtn_carrusel_ingresos = new javax.swing.JButton();
        jLabel_imagenCarrusel = new javax.swing.JLabel();
        jButton_carrusel_estadistica = new javax.swing.JButton();
        jLabel_ocupados_carrusel = new javax.swing.JLabel();
        jLabel_ingresos_carrusel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_estadis_T_ingresos = new javax.swing.JLabel();
        jLabel_estadis_Sillas_Ocupadas = new javax.swing.JLabel();
        jLabel_eatdist_sillas_vacias = new javax.swing.JLabel();
        jLabel_estadist_ocupadas = new javax.swing.JLabel();
        jLabel_estadist_juegos = new javax.swing.JLabel();
        jLabel_s_pr = new javax.swing.JLabel();
        jButton_estadist_estadist = new javax.swing.JButton();
        jLabel_s_in = new javax.swing.JLabel();
        jLabel_s_va = new javax.swing.JLabel();
        jLabel_s_oc = new javax.swing.JLabel();
        jLabel_masRecaudo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel_s_pr1 = new javax.swing.JLabel();
        jPanel_montañaRusa = new javax.swing.JPanel();
        jLabel_tipoMontaña = new javax.swing.JLabel();
        jCBox_Tipo_Montaña = new javax.swing.JComboBox<>();
        jBtn_montaña_nuevaVenta = new javax.swing.JButton();
        jButn_montaña_vaciar = new javax.swing.JButton();
        jBtn_montaña_Ocupados = new javax.swing.JButton();
        jButtn_montaña_ingresos = new javax.swing.JButton();
        jLabel_imagenCarrusel1 = new javax.swing.JLabel();
        jButton_montaña_estadistica = new javax.swing.JButton();
        jLabel_ocupados_montania = new javax.swing.JLabel();
        jLabel_ingresos_montania = new javax.swing.JLabel();
        jPanel_CarritosChocones = new javax.swing.JPanel();
        jLabel_tipoCarritosChocones = new javax.swing.JLabel();
        jCBox_Tipo_carritosChocones = new javax.swing.JComboBox<>();
        jBtn_carritosC_nuevaVenta2 = new javax.swing.JButton();
        jButn_carritosC_vaciar2 = new javax.swing.JButton();
        jBtn_carritosC_Ocupados = new javax.swing.JButton();
        jButtn_carritosC_ingresos = new javax.swing.JButton();
        jLabel_imagenCarrusel2 = new javax.swing.JLabel();
        jButn_carritosC_estadistica = new javax.swing.JButton();
        jLabel_ocupados_carritosChocones = new javax.swing.JLabel();
        jLabel_ingresos_carritosChocones = new javax.swing.JLabel();

        jDialog_carrusel_estadist.setBackground(new java.awt.Color(204, 153, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2)));
        jPanel1.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("% Ocupadas :");

        jLabel_tipoCarrusel_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_Ocupadas_porcentaje_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_sillasOcupadas_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_carrusel_ingresos_D1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel_sillasVacias_carrusel_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("== ESTADISTICA CARRUSEL ==");

        jLabel26.setText("% ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Tipo de carrusel :");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Sillas Ocupadas :");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Ingresos :");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Sillas Vacias :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel29)
                                .addComponent(jLabel28)
                                .addComponent(jLabel30)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Ocupadas_porcentaje_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_tipoCarrusel_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sillasOcupadas_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_carrusel_ingresos_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_sillasVacias_carrusel_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tipoCarrusel_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sillasOcupadas_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carrusel_ingresos_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_sillasVacias_carrusel_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Ocupadas_porcentaje_D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jDialog_carrusel_estadistLayout = new javax.swing.GroupLayout(jDialog_carrusel_estadist.getContentPane());
        jDialog_carrusel_estadist.getContentPane().setLayout(jDialog_carrusel_estadistLayout);
        jDialog_carrusel_estadistLayout.setHorizontalGroup(
            jDialog_carrusel_estadistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog_carrusel_estadistLayout.setVerticalGroup(
            jDialog_carrusel_estadistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Ingresos :");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Sillas Vacias :");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("% Ocupadas :");

        jLabel_tipoChocones_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_OcupadasPor_chocones_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_sillasOc_Chocones_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_ingresos_chocones_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_sillasVacias_chocones_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("== ESTADISTICA CARRITOS CHOCONES ==");

        jLabel35.setText("% ");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Tipo de Carritos Chocones :");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Sillas Ocupadas :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_OcupadasPor_chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_tipoChocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sillasOc_Chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sillasVacias_chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ingresos_chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tipoChocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sillasOc_Chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ingresos_chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_sillasVacias_chocones_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_OcupadasPor_chocones_D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jDialog_carritosChoconesLayout = new javax.swing.GroupLayout(jDialog_carritosChocones.getContentPane());
        jDialog_carritosChocones.getContentPane().setLayout(jDialog_carritosChoconesLayout);
        jDialog_carritosChoconesLayout.setHorizontalGroup(
            jDialog_carritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_carritosChoconesLayout.setVerticalGroup(
            jDialog_carritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Tipo de Montaña Rusa :");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Sillas Ocupadas :");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Ingresos :");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Sillas Vacias :");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("% Ocupadas :");

        jLabel_tipoMontania_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_OcupadasPor_Montania_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_sillasOcu_Montania_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_carrusel_ingre_Montania_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_sillasVacias_Montania_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setText("== ESTADISTICA  MONTAÑA RUSA ==");

        jLabel44.setText("% ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel_OcupadasPor_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_sillasVacias_Montania_D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_sillasOcu_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(78, 78, 78))
                        .addComponent(jLabel_tipoMontania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_carrusel_ingre_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tipoMontania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sillasOcu_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carrusel_ingre_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_sillasVacias_Montania_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_OcupadasPor_Montania_D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_MontaniaRusiaLayout = new javax.swing.GroupLayout(jDialog_MontaniaRusia.getContentPane());
        jDialog_MontaniaRusia.getContentPane().setLayout(jDialog_MontaniaRusiaLayout);
        jDialog_MontaniaRusiaLayout.setHorizontalGroup(
            jDialog_MontaniaRusiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog_MontaniaRusiaLayout.setVerticalGroup(
            jDialog_MontaniaRusiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times", 2, 24)); // NOI18N
        jLabel1.setText("Disney Land Park :v");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 0))); // NOI18N

        jPanel_carrusel.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_carrusel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Carrusel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_tipOCarrusel.setText("Tipo :");

        jCBox_Tipo_carrusel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasico", "Caballitos", "Tacitas Magicas" }));
        jCBox_Tipo_carrusel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBox_Tipo_carruselActionPerformed(evt);
            }
        });

        jBtn_carrusel_nuevaVenta.setText("Nueva Venta");
        jBtn_carrusel_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_carrusel_nuevaVentaActionPerformed(evt);
            }
        });

        jButn_carrusel_vaciar.setText("Vaciar");
        jButn_carrusel_vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButn_carrusel_vaciarActionPerformed(evt);
            }
        });

        jBtn_carrusel_Ocupados.setText("Ocupadas");
        jBtn_carrusel_Ocupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_carrusel_OcupadosActionPerformed(evt);
            }
        });

        jButtn_carrusel_ingresos.setText("Ingresos");
        jButtn_carrusel_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtn_carrusel_ingresosActionPerformed(evt);
            }
        });

        jLabel_imagenCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrusel.jpg"))); // NOI18N

        jButton_carrusel_estadistica.setText("Estadistica");
        jButton_carrusel_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_carrusel_estadisticaActionPerformed(evt);
            }
        });

        jLabel_ocupados_carrusel.setText("0");
        jLabel_ocupados_carrusel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_ingresos_carrusel.setText("0.00");
        jLabel_ingresos_carrusel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel_carruselLayout = new javax.swing.GroupLayout(jPanel_carrusel);
        jPanel_carrusel.setLayout(jPanel_carruselLayout);
        jPanel_carruselLayout.setHorizontalGroup(
            jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_tipOCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBox_Tipo_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_carrusel_nuevaVenta)
                            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                                .addComponent(jBtn_carrusel_Ocupados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_ocupados_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtn_carrusel_ingresos)
                            .addComponent(jButn_carrusel_vaciar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ingresos_carrusel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_carrusel_estadistica)))
                .addGap(12, 12, 12)
                .addComponent(jLabel_imagenCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_carruselLayout.setVerticalGroup(
            jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipOCarrusel)
                    .addComponent(jCBox_Tipo_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_carrusel_nuevaVenta)
                    .addComponent(jButn_carrusel_vaciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_carrusel_Ocupados)
                    .addComponent(jButtn_carrusel_ingresos)
                    .addComponent(jLabel_ocupados_carrusel)
                    .addComponent(jLabel_ingresos_carrusel))
                .addGap(18, 18, 18)
                .addComponent(jButton_carrusel_estadistica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                .addComponent(jLabel_imagenCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Estadistica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel_estadis_T_ingresos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_estadis_T_ingresos.setText("Total Ingresos :");

        jLabel_estadis_Sillas_Ocupadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_estadis_Sillas_Ocupadas.setText("Sillas Ocupadas :");

        jLabel_eatdist_sillas_vacias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_eatdist_sillas_vacias.setText("Sillas Vacias :");

        jLabel_estadist_ocupadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_estadist_ocupadas.setText("% Ocupadas :");

        jLabel_estadist_juegos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_estadist_juegos.setText("Juego con mas recaudo :");

        jLabel_s_pr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton_estadist_estadist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_estadist_estadist.setText("Ver Estadistica");
        jButton_estadist_estadist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_estadist_estadistActionPerformed(evt);
            }
        });

        jLabel_s_in.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_s_va.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_s_oc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_masRecaudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estadisticas-de-ventas.jpg"))); // NOI18N

        jLabel_s_pr1.setText("%");
        jLabel_s_pr1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton_estadist_estadist))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel_estadist_ocupadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel_eatdist_sillas_vacias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(jLabel_estadis_Sillas_Ocupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel_estadis_T_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_estadist_juegos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_masRecaudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel_s_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_s_pr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel_s_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(jLabel_s_va, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_s_oc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 139, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_s_in, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_estadis_T_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_s_oc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_s_va, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_estadis_Sillas_Ocupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_eatdist_sillas_vacias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_estadist_ocupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_s_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_s_pr1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_estadist_juegos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_masRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_estadist_estadist)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_montañaRusa.setBackground(new java.awt.Color(255, 255, 153));
        jPanel_montañaRusa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Montaña Rusa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_tipoMontaña.setText("Tipo :");

        jCBox_Tipo_Montaña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasico", "Kingda Ka", "HolidayWorld" }));
        jCBox_Tipo_Montaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBox_Tipo_MontañaActionPerformed(evt);
            }
        });

        jBtn_montaña_nuevaVenta.setText("Nueva Venta");
        jBtn_montaña_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_montaña_nuevaVentaActionPerformed(evt);
            }
        });

        jButn_montaña_vaciar.setText("Vaciar");
        jButn_montaña_vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButn_montaña_vaciarActionPerformed(evt);
            }
        });

        jBtn_montaña_Ocupados.setText("Ocupadas");
        jBtn_montaña_Ocupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_montaña_OcupadosActionPerformed(evt);
            }
        });

        jButtn_montaña_ingresos.setText("Ingresos");
        jButtn_montaña_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtn_montaña_ingresosActionPerformed(evt);
            }
        });

        jLabel_imagenCarrusel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/montaña.jpg"))); // NOI18N

        jButton_montaña_estadistica.setText("Estadistica");
        jButton_montaña_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_montaña_estadisticaActionPerformed(evt);
            }
        });

        jLabel_ocupados_montania.setText("0");
        jLabel_ocupados_montania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_ingresos_montania.setText("0.00");
        jLabel_ingresos_montania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel_montañaRusaLayout = new javax.swing.GroupLayout(jPanel_montañaRusa);
        jPanel_montañaRusa.setLayout(jPanel_montañaRusaLayout);
        jPanel_montañaRusaLayout.setHorizontalGroup(
            jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                        .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel_tipoMontaña, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBox_Tipo_Montaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_montaña_estadistica)))
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_montaña_nuevaVenta)
                            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                                .addComponent(jBtn_montaña_Ocupados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_ocupados_montania, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButn_montaña_vaciar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtn_montaña_ingresos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ingresos_montania, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_imagenCarrusel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_montañaRusaLayout.setVerticalGroup(
            jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipoMontaña)
                    .addComponent(jCBox_Tipo_Montaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_montaña_nuevaVenta)
                    .addComponent(jButn_montaña_vaciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_montañaRusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_montaña_Ocupados)
                    .addComponent(jButtn_montaña_ingresos)
                    .addComponent(jLabel_ocupados_montania)
                    .addComponent(jLabel_ingresos_montania))
                .addGap(18, 18, 18)
                .addComponent(jButton_montaña_estadistica)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel_montañaRusaLayout.createSequentialGroup()
                .addComponent(jLabel_imagenCarrusel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_CarritosChocones.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_CarritosChocones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Carritos Chocones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_tipoCarritosChocones.setText("Tipo :");

        jCBox_Tipo_carritosChocones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasico", "BateBate", "Carritos Locos" }));
        jCBox_Tipo_carritosChocones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBox_Tipo_carritosChoconesActionPerformed(evt);
            }
        });

        jBtn_carritosC_nuevaVenta2.setText("Nueva Venta");
        jBtn_carritosC_nuevaVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_carritosC_nuevaVenta2ActionPerformed(evt);
            }
        });

        jButn_carritosC_vaciar2.setText("Vaciar");
        jButn_carritosC_vaciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButn_carritosC_vaciar2ActionPerformed(evt);
            }
        });

        jBtn_carritosC_Ocupados.setText("Ocupadas");
        jBtn_carritosC_Ocupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_carritosC_OcupadosActionPerformed(evt);
            }
        });

        jButtn_carritosC_ingresos.setText("Ingresos");
        jButtn_carritosC_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtn_carritosC_ingresosActionPerformed(evt);
            }
        });

        jLabel_imagenCarrusel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carritosChocones.png"))); // NOI18N

        jButn_carritosC_estadistica.setText("Estadistica");
        jButn_carritosC_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButn_carritosC_estadisticaActionPerformed(evt);
            }
        });

        jLabel_ocupados_carritosChocones.setText("0");
        jLabel_ocupados_carritosChocones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel_ingresos_carritosChocones.setText("0.00");
        jLabel_ingresos_carritosChocones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel_CarritosChoconesLayout = new javax.swing.GroupLayout(jPanel_CarritosChocones);
        jPanel_CarritosChocones.setLayout(jPanel_CarritosChoconesLayout);
        jPanel_CarritosChoconesLayout.setHorizontalGroup(
            jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_tipoCarritosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBox_Tipo_carritosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButn_carritosC_estadistica))
                    .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_carritosC_nuevaVenta2)
                            .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                                .addComponent(jBtn_carritosC_Ocupados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_ocupados_carritosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtn_carritosC_ingresos)
                            .addComponent(jButn_carritosC_vaciar2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ingresos_carritosChocones, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_imagenCarrusel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_CarritosChoconesLayout.setVerticalGroup(
            jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipoCarritosChocones)
                    .addComponent(jCBox_Tipo_carritosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_carritosC_nuevaVenta2)
                    .addComponent(jButn_carritosC_vaciar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CarritosChoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_carritosC_Ocupados)
                    .addComponent(jButtn_carritosC_ingresos)
                    .addComponent(jLabel_ocupados_carritosChocones)
                    .addComponent(jLabel_ingresos_carritosChocones))
                .addGap(18, 18, 18)
                .addComponent(jButn_carritosC_estadistica)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel_CarritosChoconesLayout.createSequentialGroup()
                .addComponent(jLabel_imagenCarrusel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_montañaRusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel_CarritosChocones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_CarritosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_montañaRusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBox_Tipo_carruselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBox_Tipo_carruselActionPerformed
        // TODO add your handling code here:
        jCBox_Tipo_carrusel.getSelectedItem();
    }//GEN-LAST:event_jCBox_Tipo_carruselActionPerformed

    private void jBtn_carrusel_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_carrusel_nuevaVentaActionPerformed
        // TODO add your handling code here:
        carrusel.EntraUno();
        carrusel.getIngresos();
    }//GEN-LAST:event_jBtn_carrusel_nuevaVentaActionPerformed

    private void jButton_carrusel_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_carrusel_estadisticaActionPerformed
        // TODO add your handling code here:
        jDialog_carrusel_estadist.setSize(279,275);
        jDialog_carrusel_estadist.setLocation(100, 100);
        jDialog_carrusel_estadist.setVisible(true);
        jDialog_carrusel_estadist.setLocationRelativeTo(null);
        //asignando valores del jframe al dialog
        jLabel_tipoCarrusel_D1.setText(jCBox_Tipo_carrusel.getSelectedItem().toString());
        jLabel_sillasOcupadas_D1.setText(Integer.toString(carrusel.ocupados));
        jLabel_carrusel_ingresos_D1.setText(Double.toString(carrusel.getIngresos()));
        jLabel_sillasVacias_carrusel_D1.setText(Integer.toString(carrusel.getLibres()));
        jLabel_Ocupadas_porcentaje_D1.setText(Double.toString(carrusel.getPorcentaje()));
        
    }//GEN-LAST:event_jButton_carrusel_estadisticaActionPerformed

    private void jButn_carrusel_vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButn_carrusel_vaciarActionPerformed
        // TODO add your handling code here:
        jLabel_ingresos_carrusel.setText("0.00");
        jLabel_ocupados_carrusel.setText("0");
        jCBox_Tipo_carrusel.setSelectedIndex(0);
        
        carrusel.Vaciar();
    }//GEN-LAST:event_jButn_carrusel_vaciarActionPerformed

    private void jButtn_carrusel_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtn_carrusel_ingresosActionPerformed
        jLabel_ingresos_carrusel.setText(Double.toString(carrusel.getIngresos()));
    }//GEN-LAST:event_jButtn_carrusel_ingresosActionPerformed

    private void jCBox_Tipo_MontañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBox_Tipo_MontañaActionPerformed
        // TODO add your handling code here:
         jCBox_Tipo_Montaña.getSelectedItem();
    }//GEN-LAST:event_jCBox_Tipo_MontañaActionPerformed

    private void jBtn_montaña_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_montaña_nuevaVentaActionPerformed
        // TODO add your handling code here:
        carruselMontaniaRusa.EntraUno();
        carruselMontaniaRusa.getIngresos();
    }//GEN-LAST:event_jBtn_montaña_nuevaVentaActionPerformed

    private void jButn_montaña_vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButn_montaña_vaciarActionPerformed
        // TODO add your handling code here:
        jLabel_ingresos_montania.setText("0.00");
        jLabel_ocupados_montania.setText("0");
        jCBox_Tipo_Montaña.setSelectedIndex(0);
        
        carruselMontaniaRusa.Vaciar();
    }//GEN-LAST:event_jButn_montaña_vaciarActionPerformed

    private void jButtn_montaña_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtn_montaña_ingresosActionPerformed
        // TODO add your handling code here:
          jLabel_ingresos_montania.setText(Double.toString(carruselMontaniaRusa.getIngresos()));
    }//GEN-LAST:event_jButtn_montaña_ingresosActionPerformed

    private void jButton_montaña_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_montaña_estadisticaActionPerformed
        // TODO add your handling code here:
        jDialog_MontaniaRusia.setSize(275,269);
        jDialog_MontaniaRusia.setLocation(100, 100);
        jDialog_MontaniaRusia.setVisible(true);
        jDialog_MontaniaRusia.setLocationRelativeTo(null);
        //asignando valores del jframe al dialog
        jLabel_tipoMontania_D1.setText(jCBox_Tipo_Montaña.getSelectedItem().toString());
        jLabel_sillasOcu_Montania_D1.setText(Integer.toString(carruselMontaniaRusa.ocupados));
        jLabel_carrusel_ingre_Montania_D1.setText(Double.toString(carruselMontaniaRusa.getIngresos()));
        jLabel_sillasVacias_Montania_D1.setText(Integer.toString(carruselMontaniaRusa.getLibres()));
        jLabel_OcupadasPor_Montania_D1.setText(Double.toString(carruselMontaniaRusa.getPorcentaje()));
    }//GEN-LAST:event_jButton_montaña_estadisticaActionPerformed

    private void jCBox_Tipo_carritosChoconesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBox_Tipo_carritosChoconesActionPerformed
        // TODO add your handling code here:
         jCBox_Tipo_carritosChocones.getSelectedItem();
    }//GEN-LAST:event_jCBox_Tipo_carritosChoconesActionPerformed

    private void jBtn_carritosC_nuevaVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_carritosC_nuevaVenta2ActionPerformed
        // TODO add your handling code here:
        carruselCarritoChocante.EntraUno();
        carruselCarritoChocante.getIngresos();
    }//GEN-LAST:event_jBtn_carritosC_nuevaVenta2ActionPerformed

    private void jButn_carritosC_vaciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButn_carritosC_vaciar2ActionPerformed
        // TODO add your handling code here:
       jLabel_ingresos_carritosChocones.setText("0.00");
        jLabel_ocupados_carritosChocones.setText("0");
        jCBox_Tipo_carritosChocones.setSelectedIndex(0);
        
        carruselCarritoChocante.Vaciar();
    }//GEN-LAST:event_jButn_carritosC_vaciar2ActionPerformed

    private void jButtn_carritosC_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtn_carritosC_ingresosActionPerformed
        // TODO add your handling code here:
        jLabel_ingresos_carritosChocones.setText(Double.toString(carruselCarritoChocante.getIngresos()));
    }//GEN-LAST:event_jButtn_carritosC_ingresosActionPerformed

    private void jButn_carritosC_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButn_carritosC_estadisticaActionPerformed
        // TODO add your handling code here:
        jDialog_carritosChocones.setSize(310,270);
        jDialog_carritosChocones.setLocation(100, 100);
        jDialog_carritosChocones.setVisible(true);
        jDialog_carritosChocones.setLocationRelativeTo(null);
        //asignando valores del jframe al dialog
        jLabel_tipoChocones_D1.setText(jCBox_Tipo_carritosChocones.getSelectedItem().toString());
        jLabel_sillasVacias_chocones_D1.setText(Integer.toString(carruselCarritoChocante.getLibres()));
        jLabel_ingresos_chocones_D1.setText(Double.toString(carruselCarritoChocante.getIngresos()));
        jLabel_sillasOc_Chocones_D1.setText(Integer.toString(carruselCarritoChocante.ocupados));
        jLabel_OcupadasPor_chocones_D1.setText(Double.toString(carruselCarritoChocante.getPorcentaje()));
    }//GEN-LAST:event_jButn_carritosC_estadisticaActionPerformed

    private void jBtn_carrusel_OcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_carrusel_OcupadosActionPerformed
        jLabel_ocupados_carrusel.setText(Integer.toString(carrusel.ocupados));
    }//GEN-LAST:event_jBtn_carrusel_OcupadosActionPerformed

    private void jButton_estadist_estadistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_estadist_estadistActionPerformed
        Estadistica();
        Estadist_PSO();
        Mas_recaudo();
    }//GEN-LAST:event_jButton_estadist_estadistActionPerformed

    private void jBtn_carritosC_OcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_carritosC_OcupadosActionPerformed
        // TODO add your handling code here:
        jLabel_ocupados_carritosChocones.setText(Integer.toString(carruselCarritoChocante.ocupados));
    }//GEN-LAST:event_jBtn_carritosC_OcupadosActionPerformed

    private void jBtn_montaña_OcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_montaña_OcupadosActionPerformed
        // TODO add your handling code here:
        jLabel_ocupados_montania.setText(Integer.toString(carruselMontaniaRusa.ocupados));
    }//GEN-LAST:event_jBtn_montaña_OcupadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_DisneyLandPark_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_DisneyLandPark_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_DisneyLandPark_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_DisneyLandPark_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_DisneyLandPark_MarcoRath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_carritosC_Ocupados;
    private javax.swing.JButton jBtn_carritosC_nuevaVenta2;
    private javax.swing.JButton jBtn_carrusel_Ocupados;
    private javax.swing.JButton jBtn_carrusel_nuevaVenta;
    private javax.swing.JButton jBtn_montaña_Ocupados;
    private javax.swing.JButton jBtn_montaña_nuevaVenta;
    private javax.swing.JButton jButn_carritosC_estadistica;
    private javax.swing.JButton jButn_carritosC_vaciar2;
    private javax.swing.JButton jButn_carrusel_vaciar;
    private javax.swing.JButton jButn_montaña_vaciar;
    private javax.swing.JButton jButtn_carritosC_ingresos;
    private javax.swing.JButton jButtn_carrusel_ingresos;
    private javax.swing.JButton jButtn_montaña_ingresos;
    private javax.swing.JButton jButton_carrusel_estadistica;
    private javax.swing.JButton jButton_estadist_estadist;
    private javax.swing.JButton jButton_montaña_estadistica;
    private javax.swing.JComboBox<String> jCBox_Tipo_Montaña;
    private javax.swing.JComboBox<String> jCBox_Tipo_carritosChocones;
    private javax.swing.JComboBox<String> jCBox_Tipo_carrusel;
    private javax.swing.JDialog jDialog_MontaniaRusia;
    private javax.swing.JDialog jDialog_carritosChocones;
    private javax.swing.JDialog jDialog_carrusel_estadist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel_OcupadasPor_Montania_D1;
    private javax.swing.JLabel jLabel_OcupadasPor_chocones_D1;
    private javax.swing.JLabel jLabel_Ocupadas_porcentaje_D1;
    private javax.swing.JLabel jLabel_carrusel_ingre_Montania_D1;
    private javax.swing.JLabel jLabel_carrusel_ingresos_D1;
    private javax.swing.JLabel jLabel_eatdist_sillas_vacias;
    private javax.swing.JLabel jLabel_estadis_Sillas_Ocupadas;
    private javax.swing.JLabel jLabel_estadis_T_ingresos;
    private javax.swing.JLabel jLabel_estadist_juegos;
    private javax.swing.JLabel jLabel_estadist_ocupadas;
    private javax.swing.JLabel jLabel_imagenCarrusel;
    private javax.swing.JLabel jLabel_imagenCarrusel1;
    private javax.swing.JLabel jLabel_imagenCarrusel2;
    private javax.swing.JLabel jLabel_ingresos_carritosChocones;
    private javax.swing.JLabel jLabel_ingresos_carrusel;
    private javax.swing.JLabel jLabel_ingresos_chocones_D1;
    private javax.swing.JLabel jLabel_ingresos_montania;
    private javax.swing.JLabel jLabel_masRecaudo;
    private javax.swing.JLabel jLabel_ocupados_carritosChocones;
    private javax.swing.JLabel jLabel_ocupados_carrusel;
    private javax.swing.JLabel jLabel_ocupados_montania;
    private javax.swing.JLabel jLabel_s_in;
    private javax.swing.JLabel jLabel_s_oc;
    private javax.swing.JLabel jLabel_s_pr;
    private javax.swing.JLabel jLabel_s_pr1;
    private javax.swing.JLabel jLabel_s_va;
    private javax.swing.JLabel jLabel_sillasOc_Chocones_D1;
    private javax.swing.JLabel jLabel_sillasOcu_Montania_D1;
    private javax.swing.JLabel jLabel_sillasOcupadas_D1;
    private javax.swing.JLabel jLabel_sillasVacias_Montania_D1;
    private javax.swing.JLabel jLabel_sillasVacias_carrusel_D1;
    private javax.swing.JLabel jLabel_sillasVacias_chocones_D1;
    private javax.swing.JLabel jLabel_tipOCarrusel;
    private javax.swing.JLabel jLabel_tipoCarritosChocones;
    private javax.swing.JLabel jLabel_tipoCarrusel_D1;
    private javax.swing.JLabel jLabel_tipoChocones_D1;
    private javax.swing.JLabel jLabel_tipoMontania_D1;
    private javax.swing.JLabel jLabel_tipoMontaña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_CarritosChocones;
    private javax.swing.JPanel jPanel_carrusel;
    private javax.swing.JPanel jPanel_montañaRusa;
    // End of variables declaration//GEN-END:variables
}
