/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_Pizeeria_Marco;

/**
 *
 * @author Isabel
 */
public class jFrame_Ingredientes_Tamaño extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_pequeña
     */
    public jFrame_Ingredientes_Tamaño() {
        initComponents();
        //para automatisar el familiar
        jRBtn_Familiar.setSelected(true);
        this.setTitle("PIZZERIA ONLINE(MARCO RATH)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_tamaño = new javax.swing.ButtonGroup();
        jRBton_Pequeña = new javax.swing.JRadioButton();
        jRBtn_Mediana = new javax.swing.JRadioButton();
        jRBtn_Familiar = new javax.swing.JRadioButton();
        jCheckBox_Cebolla = new javax.swing.JCheckBox();
        jCheckBox_bacon = new javax.swing.JCheckBox();
        jCheckBox_Pimiento = new javax.swing.JCheckBox();
        jCheckBox_Anchoas = new javax.swing.JCheckBox();
        jBnt_Total = new javax.swing.JButton();
        Salir_boton = new javax.swing.JButton();
        costo_familiar = new javax.swing.JLabel();
        costo_mediana = new javax.swing.JLabel();
        costo_pequeña = new javax.swing.JLabel();
        ingrediente_label = new javax.swing.JLabel();
        costo_pimiento = new javax.swing.JLabel();
        costo_cebolla = new javax.swing.JLabel();
        costo_anchoas = new javax.swing.JLabel();
        costo_bacon = new javax.swing.JLabel();
        img_pimiento = new javax.swing.JLabel();
        img_anchoas = new javax.swing.JLabel();
        img_bacon = new javax.swing.JLabel();
        img_cebolla = new javax.swing.JLabel();
        img_mediana = new javax.swing.JLabel();
        jLabel_Mensaje = new javax.swing.JLabel();
        img_familiar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup_tamaño.add(jRBton_Pequeña);
        jRBton_Pequeña.setText("Pequeña");
        getContentPane().add(jRBton_Pequeña, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        buttonGroup_tamaño.add(jRBtn_Mediana);
        jRBtn_Mediana.setText("Mediana");
        getContentPane().add(jRBtn_Mediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        buttonGroup_tamaño.add(jRBtn_Familiar);
        jRBtn_Familiar.setText("Familiar");
        getContentPane().add(jRBtn_Familiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jCheckBox_Cebolla.setText("Cebolla");
        getContentPane().add(jCheckBox_Cebolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jCheckBox_bacon.setText("Bacon");
        getContentPane().add(jCheckBox_bacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jCheckBox_Pimiento.setText("Pimiento");
        getContentPane().add(jCheckBox_Pimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jCheckBox_Anchoas.setText("Anchoas");
        getContentPane().add(jCheckBox_Anchoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jBnt_Total.setText("Calcular");
        jBnt_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnt_TotalActionPerformed(evt);
            }
        });
        getContentPane().add(jBnt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        Salir_boton.setFont(new java.awt.Font("Times", 0, 36)); // NOI18N
        Salir_boton.setForeground(new java.awt.Color(204, 102, 0));
        Salir_boton.setText("X");
        Salir_boton.setBorder(null);
        Salir_boton.setBorderPainted(false);
        Salir_boton.setContentAreaFilled(false);
        Salir_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_botonActionPerformed(evt);
            }
        });
        getContentPane().add(Salir_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 90, 40));

        costo_familiar.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_familiar.setForeground(new java.awt.Color(204, 204, 0));
        costo_familiar.setText("$45");
        getContentPane().add(costo_familiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        costo_mediana.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_mediana.setForeground(new java.awt.Color(204, 204, 0));
        costo_mediana.setText("$30");
        getContentPane().add(costo_mediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, -1));

        costo_pequeña.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_pequeña.setForeground(new java.awt.Color(204, 204, 0));
        costo_pequeña.setText("$15");
        getContentPane().add(costo_pequeña, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        ingrediente_label.setFont(new java.awt.Font("Times", 0, 24)); // NOI18N
        ingrediente_label.setForeground(new java.awt.Color(153, 153, 0));
        ingrediente_label.setText("Ingredientes");
        getContentPane().add(ingrediente_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        costo_pimiento.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_pimiento.setForeground(new java.awt.Color(153, 153, 0));
        costo_pimiento.setText("$1.2");
        getContentPane().add(costo_pimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        costo_cebolla.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_cebolla.setForeground(new java.awt.Color(153, 153, 0));
        costo_cebolla.setText("$1.0");
        getContentPane().add(costo_cebolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, -1));

        costo_anchoas.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_anchoas.setForeground(new java.awt.Color(153, 153, 0));
        costo_anchoas.setText("$1.8");
        getContentPane().add(costo_anchoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        costo_bacon.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        costo_bacon.setForeground(new java.awt.Color(153, 153, 0));
        costo_bacon.setText("$1.5");
        getContentPane().add(costo_bacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        img_pimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/PIMEN.jpg"))); // NOI18N
        img_pimiento.setText("jLabel10");
        getContentPane().add(img_pimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 210, 160));

        img_anchoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/cho.jpg"))); // NOI18N
        img_anchoas.setText("jLabel9");
        getContentPane().add(img_anchoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, 160));

        img_bacon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/bac.jpg"))); // NOI18N
        getContentPane().add(img_bacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 160));

        img_cebolla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/CEB.jpg"))); // NOI18N
        getContentPane().add(img_cebolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, 180));

        img_mediana.setFont(new java.awt.Font("Times", 2, 36)); // NOI18N
        img_mediana.setForeground(new java.awt.Color(153, 153, 0));
        img_mediana.setText("TAMANO");
        getContentPane().add(img_mediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 160, 40));

        jLabel_Mensaje.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        jLabel_Mensaje.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_Mensaje.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 300, 60));

        img_familiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/fam.jpg"))); // NOI18N
        img_familiar.setText("jLabel4");
        getContentPane().add(img_familiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 520, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/media.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 260, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/peq.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 280, 140));

        jLabel1.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/diseno-fondo-textura-madera-nogal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jpack_Imagenes/diseno-fondo-textura-madera-nogal.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 420, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnt_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnt_TotalActionPerformed
        //mensaje de salida
        String Mensaje= "Total A Pagar es: ";
        //acumulador para el mensaje
        float acumulador=0;
        //si selecciona familiar
        if(jRBtn_Familiar.isSelected()){
            //costo de la familiar
            float familiar= 45;
            //si selecciona bacon
            if(jCheckBox_bacon.isSelected()){
                float bacon=(float)1.5;
                familiar=familiar+bacon;
            }
            if(jCheckBox_Anchoas.isSelected()){
                float anchoas=(float) 1.8;
                familiar=familiar+anchoas;
            }
            if(jCheckBox_Cebolla.isSelected()){
                float cebolla=1; 
                familiar=familiar +cebolla;
            }
            if(jCheckBox_Pimiento.isSelected()){
                float pimiento=(float) 1.2;
                familiar=familiar+pimiento;
            }
            //acumulando valores seleccionados
            acumulador=acumulador +familiar;
            //muestra el mensaje + el costo que se selecciono
            Mensaje= Mensaje + acumulador;
        }
        else if(jRBtn_Mediana.isSelected()){
            float mediana=30;
            if(jCheckBox_bacon.isSelected()){
                float bacon=(float) 1.5;
                mediana=mediana+bacon;
            }
            if(jCheckBox_Anchoas.isSelected()){
                float anchoas=(float) 1.8;
                mediana=mediana+anchoas;
            }
            if(jCheckBox_Cebolla.isSelected()){
                float cebolla=1; 
                mediana=mediana +cebolla;
            }
            if(jCheckBox_Pimiento.isSelected()){
                float pimiento=(float) 1.2;
                mediana=mediana+pimiento;
            }
            acumulador=acumulador + mediana;
            Mensaje=Mensaje+ acumulador;
        }
        else if (jRBton_Pequeña.isSelected()){
            float pequeña=15;
            if(jCheckBox_bacon.isSelected()){
                float bacon=(float) 1.5;
                pequeña=pequeña+bacon;
            }
            if(jCheckBox_Anchoas.isSelected()){
                float anchoas=(float ) 1.8;
                pequeña=pequeña+anchoas;
            }
            if(jCheckBox_Cebolla.isSelected()){
                float cebolla=1; 
                pequeña=pequeña +cebolla;
            }
            if(jCheckBox_Pimiento.isSelected()){
                float pimiento=(float) 1.2;
              pequeña=pequeña+pimiento;
            }
            acumulador=acumulador + pequeña;
            Mensaje=Mensaje + acumulador;
        }
        jLabel_Mensaje.setText(Mensaje);
    }//GEN-LAST:event_jBnt_TotalActionPerformed

    private void Salir_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_botonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Salir_botonActionPerformed
                                 

  
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Ingredientes_Tamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Ingredientes_Tamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Ingredientes_Tamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Ingredientes_Tamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Ingredientes_Tamaño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir_boton;
    private javax.swing.ButtonGroup buttonGroup_tamaño;
    private javax.swing.JLabel costo_anchoas;
    private javax.swing.JLabel costo_bacon;
    private javax.swing.JLabel costo_cebolla;
    private javax.swing.JLabel costo_familiar;
    private javax.swing.JLabel costo_mediana;
    private javax.swing.JLabel costo_pequeña;
    private javax.swing.JLabel costo_pimiento;
    private javax.swing.JLabel img_anchoas;
    private javax.swing.JLabel img_bacon;
    private javax.swing.JLabel img_cebolla;
    private javax.swing.JLabel img_familiar;
    private javax.swing.JLabel img_mediana;
    private javax.swing.JLabel img_pimiento;
    private javax.swing.JLabel ingrediente_label;
    private javax.swing.JButton jBnt_Total;
    private javax.swing.JCheckBox jCheckBox_Anchoas;
    private javax.swing.JCheckBox jCheckBox_Cebolla;
    private javax.swing.JCheckBox jCheckBox_Pimiento;
    private javax.swing.JCheckBox jCheckBox_bacon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Mensaje;
    private javax.swing.JRadioButton jRBtn_Familiar;
    private javax.swing.JRadioButton jRBtn_Mediana;
    private javax.swing.JRadioButton jRBton_Pequeña;
    // End of variables declaration//GEN-END:variables
}
