
package jPack_MiAgenda_MarcoRath;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class jFrame_MarcoAntonio extends javax.swing.JFrame {
DefaultTableModel modelotabla;
    /**
     * Creates new form jFrame_MarcoAntonio
     */
    public jFrame_MarcoAntonio() {
        initComponents();
        preparartabla();
        
    }

    void preparartabla(){
    //etiqueta,declarar un vector d tipo Strin
    String etiquetasup[]={"Nombre","Apellidos","Edad","Signo"};
        // datos de la tabla
         modelotabla = new DefaultTableModel(null,etiquetasup);
        //null significa que la tabla esta vacia
        //etiquetasup es el encabezado o titulo de la tabla
   
    //asignar al modelo al objeto tabla
    jTable_misamigos.setModel(modelotabla);
    
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_misamigos = new javax.swing.JTable();
        jbtn_agregarfila = new javax.swing.JButton();
        jbtn_eliminarfila = new javax.swing.JButton();
        jbtn_nuevoamigo = new javax.swing.JButton();
        jbtn_mostrar = new javax.swing.JButton();
        label_fila = new javax.swing.JLabel();
        label_columna = new javax.swing.JLabel();
        label_mostrarelementos = new javax.swing.JLabel();
        jbtn_introducirelemento = new javax.swing.JButton();
        label_mostrarElementos = new javax.swing.JLabel();
        jtxt_introducir = new javax.swing.JTextField();
        jtxt_fila = new javax.swing.JTextField();
        jtxt_columna = new javax.swing.JTextField();
        jbtn_pintar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_titulo.setFont(new java.awt.Font("Times", 2, 24)); // NOI18N
        jLabel1_titulo.setText("Mi Agenda(Tabla)");

        jTable_misamigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_misamigos);

        jbtn_agregarfila.setText("Agregar Fila");
        jbtn_agregarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarfilaActionPerformed(evt);
            }
        });

        jbtn_eliminarfila.setText("Eliminar Fila");
        jbtn_eliminarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarfilaActionPerformed(evt);
            }
        });

        jbtn_nuevoamigo.setText("Nuevo Amigo");
        jbtn_nuevoamigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoamigoActionPerformed(evt);
            }
        });

        jbtn_mostrar.setText("Mostrar");
        jbtn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_mostrarActionPerformed(evt);
            }
        });

        label_fila.setText("Fila");

        label_columna.setText("Columna");

        label_mostrarelementos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jbtn_introducirelemento.setText("Introducir Elemento");
        jbtn_introducirelemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_introducirelementoActionPerformed(evt);
            }
        });

        label_mostrarElementos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));

        jtxt_introducir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jtxt_fila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0)));

        jtxt_columna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jbtn_pintar.setText("Pintar");
        jbtn_pintar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pintarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_introducirelemento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(label_columna)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_mostrarelementos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_mostrar)
                                .addGap(18, 18, 18)
                                .addComponent(label_mostrarElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jtxt_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtn_agregarfila)
                        .addGap(51, 51, 51)
                        .addComponent(jbtn_eliminarfila)
                        .addGap(41, 41, 41)
                        .addComponent(jbtn_nuevoamigo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtn_pintar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_titulo)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_agregarfila)
                            .addComponent(jbtn_eliminarfila)
                            .addComponent(jbtn_nuevoamigo))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_columna))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxt_introducir)
                                    .addComponent(jtxt_fila)
                                    .addComponent(jtxt_columna, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn_mostrar)
                                    .addComponent(label_mostrarElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(label_mostrarelementos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jbtn_introducirelemento)
                .addGap(18, 18, 18)
                .addComponent(jbtn_pintar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarfilaActionPerformed
        //asignar el modelo de la tabla en la variable ModeloTabla(getmodel)
        modelotabla = (DefaultTableModel) jTable_misamigos.getModel();
        //crear un vector para un amigo(4 campos)
        String filavacia[]=new String[4];
        //agregar filavacia al modelo
        //rom=fila
        modelotabla.addRow(filavacia);
     
    }//GEN-LAST:event_jbtn_agregarfilaActionPerformed

    private void jbtn_nuevoamigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoamigoActionPerformed
     modelotabla=(DefaultTableModel) jTable_misamigos.getModel();
     String filaelemento[]={"YEFERSON","ESPINOZA","20","TAURO"};
     modelotabla.addRow(filaelemento);
    }//GEN-LAST:event_jbtn_nuevoamigoActionPerformed

    private void jbtn_eliminarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarfilaActionPerformed
    //eliminar fila debe verificar que exista una fila seleccionada
    //getSelectRow devuelve un # este # es el de la fila seleccionada,al no exixstir una fila seleccionada debuelbe
    //-1
    
    int filaseleccionada=jTable_misamigos.getSelectedRow();
    //preguntar si la respuesta es diferente de -1(osea existe seleccion)
    if(filaseleccionada>-1){
    modelotabla=(DefaultTableModel) jTable_misamigos.getModel();
    modelotabla.removeRow(filaseleccionada);
    }
    else{//si es -1 no existe la fila
        JOptionPane.showMessageDialog(null,"Seleccione una fila");
        
    
    }
    }//GEN-LAST:event_jbtn_eliminarfilaActionPerformed

    private void jbtn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_mostrarActionPerformed
       //declarar variables auxiliares
        int fila;
       int columna;
       String valor;
       try{
       //obtener valores ingresados
       fila=Integer.parseInt(jtxt_fila.getText());
       columna=Integer.parseInt(jtxt_columna.getText());
       //obtener el modelo de la tabla 
       modelotabla=(DefaultTableModel) jTable_misamigos.getModel();
       //obtener el texto del campo(getValueAt)
       valor=(String) modelotabla.getValueAt(fila, columna);
       label_mostrarElementos.setText(valor);
       
       }
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null, "...ERROR..Filas o Columnas Incorrectas ");
       }   
           
    }//GEN-LAST:event_jbtn_mostrarActionPerformed

    private void jbtn_introducirelementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_introducirelementoActionPerformed
     int fila,columna;
     String textointroducido;
     try{
     //recuperar los valores de la fila y columna introducidospor el usuario
     fila=Integer.parseInt(jtxt_fila.getText());
     columna=Integer.parseInt(jtxt_columna.getText());
     textointroducido=jtxt_introducir.getText();
     modelotabla=(DefaultTableModel) jTable_misamigos.getModel();
     modelotabla.setValueAt(textointroducido ,fila, columna);
     }
     catch(Exception e)
     {
     JOptionPane.showMessageDialog(null,"..Error...en Fila o Columna");
     
     }
     
    }//GEN-LAST:event_jbtn_introducirelementoActionPerformed

    private void jbtn_pintarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pintarActionPerformed
     int Fila, Columna;
        
        try{
            
            Fila = Integer.parseInt(jtxt_fila.getText());
            Columna = Integer.parseInt(jtxt_columna.getText());
            
             pintarCelda(jTable_misamigos, Fila, Columna, Color.GREEN);
            
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "....Erorrrrrr....");
            
        }
    }                                           

     public static void pintarCelda(JTable tabla, int fila, int columna, Color color) {
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setBackground(color);
        tabla.getColumnModel().getColumn(columna).setCellRenderer(renderer);

        // Obtener la celda específica y forzar su repintado
        Rectangle rect = tabla.getCellRect(fila, columna, true);
        tabla.repaint(rect);
    
    }//GEN-LAST:event_jbtn_pintarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_MarcoAntonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_MarcoAntonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_MarcoAntonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_MarcoAntonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_MarcoAntonio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_misamigos;
    private javax.swing.JButton jbtn_agregarfila;
    private javax.swing.JButton jbtn_eliminarfila;
    private javax.swing.JButton jbtn_introducirelemento;
    private javax.swing.JButton jbtn_mostrar;
    private javax.swing.JButton jbtn_nuevoamigo;
    private javax.swing.JButton jbtn_pintar;
    private javax.swing.JTextField jtxt_columna;
    private javax.swing.JTextField jtxt_fila;
    private javax.swing.JTextField jtxt_introducir;
    private javax.swing.JLabel label_columna;
    private javax.swing.JLabel label_fila;
    private javax.swing.JLabel label_mostrarElementos;
    private javax.swing.JLabel label_mostrarelementos;
    // End of variables declaration//GEN-END:variables
}
