
package jPack_Animales_MarcoRath;

import java.awt.HeadlessException;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.ImageIcon;


public class jFrame_Animales_MarcoRath extends javax.swing.JFrame {

    public jFrame_Animales_MarcoRath(ButtonGroup boton_agrupar, JButton ejecutar, JButton jbtn_salir, JLabel label_imagen, JLabel label_resultado, JPanel panel_principal, JRadioButton radio_agila, JRadioButton radio_gato, JRadioButton radio_perro, JRadioButton radio_zorro) throws HeadlessException {
        this.boton_agrupar = boton_agrupar;
        this.ejecutar = ejecutar;
        this.jbtn_salir = jbtn_salir;
        this.label_imagen = label_imagen;
        this.label_resultado = label_resultado;
        this.panel_principal = panel_principal;
        this.radio_agila = radio_agila;
        this.radio_gato = radio_gato;
        this.radio_perro = radio_perro;
        this.radio_zorro = radio_zorro;
    }

    public jFrame_Animales_MarcoRath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_agrupar = new javax.swing.ButtonGroup();
        panel_principal = new javax.swing.JPanel();
        radio_zorro = new javax.swing.JRadioButton();
        radio_agila = new javax.swing.JRadioButton();
        radio_perro = new javax.swing.JRadioButton();
        radio_gato = new javax.swing.JRadioButton();
        jbtn_salir = new javax.swing.JButton();
        ejecutar = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();
        label_imagen = new javax.swing.JLabel();
        salir_jbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliga alguna opcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        boton_agrupar.add(radio_zorro);
        radio_zorro.setText("Zorro");

        boton_agrupar.add(radio_agila);
        radio_agila.setText("Aguila");

        boton_agrupar.add(radio_perro);
        radio_perro.setText("Perro");

        boton_agrupar.add(radio_gato);
        radio_gato.setText("Gato");

        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_zorro)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(radio_agila)
                                .addGap(63, 63, 63)
                                .addComponent(ejecutar))
                            .addComponent(radio_perro)
                            .addComponent(radio_gato))
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addComponent(jbtn_salir)
                        .addGap(38, 38, 38))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_agila)
                    .addComponent(ejecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_zorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_perro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_gato)
                .addGap(168, 168, 168)
                .addComponent(jbtn_salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        label_imagen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));

        salir_jbtn.setText("Salir");
        salir_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_jbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(salir_jbtn)))
                        .addGap(34, 34, 34)
                        .addComponent(label_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salir_jbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
   String mensaje = ""; // Declarar la variable mensaje una vez antes de los bloques if
    ImageIcon imagen = null;

    // Preguntas qué botón se seleccionó
    if (radio_agila.isSelected()) {
        mensaje += "Animal Astuto: ";
        mensaje += "Águila";
        imagen = new ImageIcon("D:\\imgfotos\\aguila.PNG");
    }
    if (radio_zorro.isSelected()) {
        mensaje += "Pertenece a los rapaces: ";
        mensaje += "Águila";
        imagen = new ImageIcon("D:\\imgfotos\\zorro.PNG");
    }
    if (radio_perro.isSelected()) {
        mensaje += "Animal Canino: ";
        mensaje += "Perro";
        imagen = new ImageIcon("D:\\imgfotos\\perro.PNG");
    }
    if (radio_gato.isSelected()) {
        mensaje += "Animal Felino: ";
        mensaje += "Gato";
        imagen = new ImageIcon("D:\\imgfotos\\gato.PNG");
    }

    label_resultado.setText(mensaje);
    label_imagen.setIcon(imagen);
   
    }//GEN-LAST:event_ejecutarActionPerformed

    private void salir_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_jbtnActionPerformed
       this.dispose();
    }//GEN-LAST:event_salir_jbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Animales_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Animales_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Animales_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Animales_MarcoRath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Animales_MarcoRath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boton_agrupar;
    private javax.swing.JButton ejecutar;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JRadioButton radio_agila;
    private javax.swing.JRadioButton radio_gato;
    private javax.swing.JRadioButton radio_perro;
    private javax.swing.JRadioButton radio_zorro;
    private javax.swing.JButton salir_jbtn;
    // End of variables declaration//GEN-END:variables
}
