/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template


*/
package jPack_MisRecuerdos;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JTextArea;
    

public class jFrame_MisRecuerdos extends javax.swing.JFrame {
  
    private static int MAXIMIEED_BOTH;

    /**
     * Creates new form jFrame_MisRecuerdos
     */
    public jFrame_MisRecuerdos() {
        initComponents();
        
        configurarventana();
    }
 //ESTAMOS HACIENDO EL MDI
    public void configurarventana(){
    this.setSize(500,500);
    this.setExtendedState(jFrame_MisRecuerdos.MAXIMIEED_BOTH);
         
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1_panelinterno = new javax.swing.JDesktopPane();
        jMenuBar1_misrecuerdos = new javax.swing.JMenuBar();
        jMenu1_archivos = new javax.swing.JMenu();
        jMenuItem1_abrir = new javax.swing.JMenuItem();
        jMenuItem1_cerrar1 = new javax.swing.JMenuItem();
        jMenuItem1_cerrartodo = new javax.swing.JMenuItem();
        jSeparator1_archivo = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_salir = new javax.swing.JMenuItem();
        jMenu2_salir = new javax.swing.JMenu();
        jMenu1_Ventana = new javax.swing.JMenu();
        jMenuItem1_cascada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1_panelinternoLayout = new javax.swing.GroupLayout(jDesktopPane1_panelinterno);
        jDesktopPane1_panelinterno.setLayout(jDesktopPane1_panelinternoLayout);
        jDesktopPane1_panelinternoLayout.setHorizontalGroup(
            jDesktopPane1_panelinternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jDesktopPane1_panelinternoLayout.setVerticalGroup(
            jDesktopPane1_panelinternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1_panelinterno, java.awt.BorderLayout.CENTER);

        jMenu1_archivos.setText("Archivo");

        jMenuItem1_abrir.setText("Abrir");
        jMenuItem1_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_abrirActionPerformed(evt);
            }
        });
        jMenu1_archivos.add(jMenuItem1_abrir);

        jMenuItem1_cerrar1.setText("Cerrar");
        jMenuItem1_cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_cerrar1ActionPerformed(evt);
            }
        });
        jMenu1_archivos.add(jMenuItem1_cerrar1);

        jMenuItem1_cerrartodo.setText("Cerrar Todo");
        jMenuItem1_cerrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_cerrartodoActionPerformed(evt);
            }
        });
        jMenu1_archivos.add(jMenuItem1_cerrartodo);
        jMenu1_archivos.add(jSeparator1_archivo);

        jMenuItem1_salir.setText("Salir");
        jMenu1_archivos.add(jMenuItem1_salir);

        jMenuBar1_misrecuerdos.add(jMenu1_archivos);

        jMenu2_salir.setText("Salir");
        jMenu2_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2_salirActionPerformed(evt);
            }
        });
        jMenuBar1_misrecuerdos.add(jMenu2_salir);

        jMenu1_Ventana.setText("Ventana");

        jMenuItem1_cascada.setText("Cascada");
        jMenuItem1_cascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_cascadaActionPerformed(evt);
            }
        });
        jMenu1_Ventana.add(jMenuItem1_cascada);

        jMenuBar1_misrecuerdos.add(jMenu1_Ventana);

        setJMenuBar(jMenuBar1_misrecuerdos);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_abrirActionPerformed
       JFileChooser Abrir=new JFileChooser(); 
       int Boton =Abrir.showOpenDialog(null);
       if(Boton==JFileChooser.APPROVE_OPTION){
       //ventana interna
       jInternalFrame_Imagenes VI=new jInternalFrame_Imagenes(); 
      //cambiar de tamaño
      VI.setResizable(true);
      //maximisar 
      VI.setMaximizable(true);
      //minimizar
      VI.setIconifiable(true);
      //cerrar
      VI.setClosable(true);
      //agregar la ventana interna IV al panel interno
      jDesktopPane1_panelinterno.add(VI); 
      //colocar la imagen en la ventana interna VI y mostrarla
      String Camino="";
      Camino=Abrir.getSelectedFile().toString();
      //colocar la imagen dentro del Label
      VI.SetImagen(Camino);
      //colocar la ruta o el camino en la imagen en la VI
      VI.setTitle(Camino);
      //hacer visible la VI
      VI.setVisible(true);
      
      
      
      
      
       
       }
    }//GEN-LAST:event_jMenuItem1_abrirActionPerformed

    private void jMenuItem1_cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_cerrar1ActionPerformed
      //determinar que VI esta activa
   jInternalFrame_Imagenes VActiva = (jInternalFrame_Imagenes)jDesktopPane1_panelinterno.getSelectedFrame();
      if(VActiva!=null){
          
      jDesktopPane1_panelinterno.getAllFrames();  
      VActiva.dispose();
            
      }
    }//GEN-LAST:event_jMenuItem1_cerrar1ActionPerformed


    private void jMenuItem1_cerrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_cerrartodoActionPerformed
 JInternalFrame[] frames = jDesktopPane1_panelinterno.getAllFrames();
for (JInternalFrame frame : frames) {
    frame.dispose(); 
    }
     
    }//GEN-LAST:event_jMenuItem1_cerrartodoActionPerformed
    
    private void jMenuItem1_cascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_cascadaActionPerformed
    JInternalFrame[] frames = jDesktopPane1_panelinterno.getAllFrames();
    int Vari1 = 0,Vari2 = 0,Acum = 30;
    for (JInternalFrame frame : frames) {
        frame.setLocation(Vari1, Vari2);
        Vari1 =Vari1+ Acum;
        Vari2 =Vari2+ Acum;
        if (Vari1+ frame.getWidth() > jDesktopPane1_panelinterno.getWidth()) {
            Vari1 = 0;
        }
        if (Vari2 + frame.getHeight() > jDesktopPane1_panelinterno.getHeight()) {
            Vari2 = 0;
        }
    }
      
       
    }//GEN-LAST:event_jMenuItem1_cascadaActionPerformed

    private void jMenu2_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2_salirActionPerformed
       dispose();
    }//GEN-LAST:event_jMenu2_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisRecuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisRecuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisRecuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisRecuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_MisRecuerdos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1_panelinterno;
    private javax.swing.JMenu jMenu1_Ventana;
    private javax.swing.JMenu jMenu1_archivos;
    private javax.swing.JMenu jMenu2_salir;
    private javax.swing.JMenuBar jMenuBar1_misrecuerdos;
    private javax.swing.JMenuItem jMenuItem1_abrir;
    private javax.swing.JMenuItem jMenuItem1_cascada;
    private javax.swing.JMenuItem jMenuItem1_cerrar1;
    private javax.swing.JMenuItem jMenuItem1_cerrartodo;
    private javax.swing.JMenuItem jMenuItem1_salir;
    private javax.swing.JPopupMenu.Separator jSeparator1_archivo;
    // End of variables declaration//GEN-END:variables
}
