/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jFrame_Termometro;
import javax.swing.*;
import javax.swing.event.*;

public class jFrame_termometro extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_termometro
     */
    public jFrame_termometro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider_farenge = new javax.swing.JSlider();
        celcios_slider = new javax.swing.JSlider();
        label_celcios = new javax.swing.JLabel();
        labe_farenge = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slider_farenge.setBackground(new java.awt.Color(204, 204, 204));
        slider_farenge.setMaximum(200);
        slider_farenge.setMinimum(4);
        slider_farenge.setOrientation(javax.swing.JSlider.VERTICAL);
        slider_farenge.setPaintLabels(true);
        slider_farenge.setPaintTicks(true);
        slider_farenge.setValue(32);
        slider_farenge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_farengeStateChanged(evt);
            }
        });
        getContentPane().add(slider_farenge, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 290));

        celcios_slider.setBackground(new java.awt.Color(204, 204, 204));
        celcios_slider.setMaximum(200);
        celcios_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        celcios_slider.setPaintLabels(true);
        celcios_slider.setPaintTicks(true);
        celcios_slider.setValue(0);
        celcios_slider.setMaximumSize(new java.awt.Dimension(28, 36));
        celcios_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                celcios_sliderStateChanged(evt);
            }
        });
        getContentPane().add(celcios_slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 300));

        label_celcios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        getContentPane().add(label_celcios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 190, 30));

        labe_farenge.setBackground(new java.awt.Color(153, 0, 51));
        labe_farenge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 51)));
        getContentPane().add(labe_farenge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_term/ter.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 51)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celcios_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_celcios_sliderStateChanged
       label_celcios.setText("El termometro esta : "+ celcios_slider.getValue() + " ºC");
       celcios_slider.addChangeListener(e -> {
            slider_farenge.setValue((int)(celcios_slider.getValue() * 1.8 + 32));
            label_celcios.setText(celcios_slider.getValue() + "°C");
            labe_farenge.setText(slider_farenge.getValue() + "°F");
        });
    
         
    }//GEN-LAST:event_celcios_sliderStateChanged

    private void slider_farengeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_farengeStateChanged
      labe_farenge.setText("Eltermometro esta en :"+ slider_farenge.getValue()+" ºF");
      slider_farenge.addChangeListener(e -> {
            celcios_slider.setValue((int)((slider_farenge.getValue() - 32) / 1.8));
            label_celcios.setText(celcios_slider.getValue() + "°C");
            labe_farenge.setText(slider_farenge.getValue() + "°F");
        });
           
    }//GEN-LAST:event_slider_farengeStateChanged

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_termometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider celcios_slider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labe_farenge;
    private javax.swing.JLabel label_celcios;
    private javax.swing.JSlider slider_farenge;
    // End of variables declaration//GEN-END:variables
}
