
package jPack_Termometro_Caja;

import java.awt.Color;
import static java.lang.System.exit;
import javax.swing.JOptionPane;

public class jFrame_CajaFuerte extends javax.swing.JFrame {

   
    public jFrame_CajaFuerte() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        boton_salir = new javax.swing.JButton();
        spinner1 = new javax.swing.JSpinner();
        spinner2 = new javax.swing.JSpinner();
        spinner3 = new javax.swing.JSpinner();
        spinner4 = new javax.swing.JSpinner();
        spinner5 = new javax.swing.JSpinner();
        label_resultado = new javax.swing.JLabel();
        boton_abrir = new javax.swing.JButton();
        img_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setBackground(new java.awt.Color(0, 153, 102));
        label_titulo.setFont(new java.awt.Font("Times", 2, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(0, 51, 51));
        label_titulo.setText("   BOX");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, -1));

        boton_salir.setBackground(new java.awt.Color(255, 255, 255));
        boton_salir.setFont(new java.awt.Font("Times", 2, 36)); // NOI18N
        boton_salir.setForeground(new java.awt.Color(0, 51, 51));
        boton_salir.setText("x");
        boton_salir.setDoubleBuffered(true);
        boton_salir.setFocusCycleRoot(true);
        boton_salir.setFocusTraversalPolicyProvider(true);
        boton_salir.setHideActionText(true);
        boton_salir.setInheritsPopupMenu(true);
        boton_salir.setRequestFocusEnabled(false);
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 30));
        getContentPane().add(spinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 44, 33));
        getContentPane().add(spinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 44, 36));
        getContentPane().add(spinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 44, 32));
        getContentPane().add(spinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 44, 31));
        getContentPane().add(spinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 44, 32));

        label_resultado.setBackground(new java.awt.Color(0, 0, 0));
        label_resultado.setFont(new java.awt.Font("Times", 2, 24)); // NOI18N
        label_resultado.setForeground(new java.awt.Color(0, 102, 102));
        label_resultado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, 50));

        boton_abrir.setBackground(new java.awt.Color(255, 255, 255));
        boton_abrir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_abrir.setForeground(new java.awt.Color(0, 51, 51));
        boton_abrir.setText("Abrir Caja");
        boton_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_abrirActionPerformed(evt);
            }
        });
        getContentPane().add(boton_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 126, -1));

        img_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/box_1.jpg"))); // NOI18N
        getContentPane().add(img_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 470, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int count = 0;
    private void boton_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_abrirActionPerformed
        // TODO add your handling code here:
         count++;
        if(count>=3){
        JOptionPane.showMessageDialog(null,"solo se pueden seleccionar 3 veces.","Error",JOptionPane.ERROR_MESSAGE);
      
        }
        //declarando variables para la salida del spinner 
        String num1=spinner1.getValue().toString();
        String num2=spinner2.getValue().toString();
        String num3=spinner3.getValue().toString();
        String num4=spinner4.getValue().toString();
        String num5=spinner5.getValue().toString();
        //declarando variables nuevas para el valor del spinner 
        int numero1 = Integer.parseInt(num1);
        int numero2 = Integer.parseInt(num2);
        int numero3= Integer.parseInt(num3);
        int numero4 = Integer.parseInt(num4);
        int numero5 = Integer.parseInt(num5);
        //condicion para la clave 
        if(numero1==1 ){
            if(numero2==2 ){
                if(numero3==3 ){
                    if(numero4==4 ){
                        if(numero5==5 ){
                         label_resultado.setText("Correcto");
                         label_resultado.setForeground(Color.blue);
                        }else{
                        label_resultado.setText("intente de nuevo");
                         label_resultado.setForeground(Color.red);
                        }
                    }else{
                    label_resultado.setText("intente de nuevo");
                     label_resultado.setForeground(Color.red);
                    }
                }else{
                  label_resultado.setText("intente de nuevo");
                     label_resultado.setForeground(Color.red);  
                }
            } else{
               label_resultado.setText("intente de nuevo");
                label_resultado.setForeground(Color.red); 
            } 
        }else {
        label_resultado.setText("intente de nuevo");
        label_resultado.setForeground(Color.red);
        }
    }//GEN-LAST:event_boton_abrirActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
     this.dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_CajaFuerte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_CajaFuerte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_CajaFuerte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_CajaFuerte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_CajaFuerte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_abrir;
    private javax.swing.JButton boton_salir;
    private javax.swing.JLabel img_label;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JSpinner spinner1;
    private javax.swing.JSpinner spinner2;
    private javax.swing.JSpinner spinner3;
    private javax.swing.JSpinner spinner4;
    private javax.swing.JSpinner spinner5;
    // End of variables declaration//GEN-END:variables
}
