
package jPack_Tienda_MarcoRath;

import jPack_Tienda_MarcoRath.jClass_Prendas_Vestir;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class jFrame_calsado extends javax.swing.JFrame {

private jClass_Prendas_Vestir tiendaRopa;
private StringBuilder productosSeleccionados = new StringBuilder();

 private int precioAcumulado = 0;
    public jFrame_calsado() {
      this.tiendaRopa = new jClass_Prendas_Vestir(); // Crear una instancia de jClass_Prendas_Vestir y asignarla a this.tiendaRopa
    int precioAlbarca = tiendaRopa.getprecioAlbarca();
    int precioAlpargata = tiendaRopa.getprecioAlpargata();
    int precioBabucha = tiendaRopa.getprecioBabucha();
    int precioBotas = tiendaRopa.getprecioBotas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_agrupar = new javax.swing.ButtonGroup();
        radio_Babucha = new javax.swing.JCheckBox();
        jbtn_limpiar = new javax.swing.JButton();
        radio_Botas = new javax.swing.JCheckBox();
        jbtn_atras = new javax.swing.JButton();
        jbtn_estadistica = new javax.swing.JButton();
        jbtn_comprar = new javax.swing.JButton();
        label_icono = new javax.swing.JLabel();
        label_concepto = new javax.swing.JLabel();
        radio_Albarca = new javax.swing.JCheckBox();
        radio_Alpargata = new javax.swing.JCheckBox();
        jbtn_aceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_agrupar.add(radio_Babucha);
        radio_Babucha.setText("Babucha");
        getContentPane().add(radio_Babucha, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 21, -1, -1));

        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 342, -1, -1));

        boton_agrupar.add(radio_Botas);
        radio_Botas.setText("Paloma");
        getContentPane().add(radio_Botas, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 21, -1, -1));

        jbtn_atras.setText("Atras");
        jbtn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 383, -1, -1));

        jbtn_estadistica.setText("Estadistica");
        jbtn_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_estadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 342, -1, -1));

        jbtn_comprar.setText("Comprar");
        jbtn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 386, -1, -1));

        label_icono.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 59, 686, 271));

        label_concepto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 421, 351, 71));

        boton_agrupar.add(radio_Albarca);
        radio_Albarca.setText("Albarca");
        getContentPane().add(radio_Albarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 21, -1, -1));

        boton_agrupar.add(radio_Alpargata);
        radio_Alpargata.setText("Alpargata");
        getContentPane().add(radio_Alpargata, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 21, -1, -1));

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 345, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
        radio_Albarca.setSelected(false);
        radio_Alpargata.setSelected(false);
        radio_Babucha.setSelected(false);
        radio_Botas.setSelected(false);
        label_concepto.setText("");
        label_icono.setIcon(null);
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jbtn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasActionPerformed
        jFrame_Seleccion seleccion=new jFrame_Seleccion();
        seleccion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_atrasActionPerformed

    private void jbtn_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_estadisticaActionPerformed
        String seleccionados = "";

        if (radio_Albarca.isSelected()) {
            seleccionados += "Albarca\n";
        }
        if (radio_Alpargata.isSelected()) {
            seleccionados += "Alpargata\n";
        }
        if (radio_Babucha.isSelected()) {
            seleccionados += "Babucha\n";
        }
        if (radio_Botas.isSelected()) {
            seleccionados += "Botas\n";
        }

        String mensaje = "Elementos seleccionados:\n" + productosSeleccionados.toString() + "\nPrecio acumulado: " + precioAcumulado;
    JOptionPane.showMessageDialog(this, mensaje);

    }//GEN-LAST:event_jbtn_estadisticaActionPerformed

    private void jbtn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_comprarActionPerformed
        int precioSeleccionado = 0;

        if (radio_Albarca.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioAlbarca();
        } else if (radio_Alpargata.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioAlpargata();
        } else if (radio_Babucha.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioBabucha();
        } else if (radio_Botas.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioBotas();
        }

        precioAcumulado += precioSeleccionado;

        String mensaje = "¡Has comprado un calsado!\nPrecio acumulado: " + precioAcumulado;
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jbtn_comprarActionPerformed

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        String mensaje = ""; // Declarar la variable mensaje una vez antes de los bloques if
        ImageIcon imagen = null;

        // Preguntas qué botón se seleccionó
             if (radio_Albarca.isSelected()) {
        mensaje += "Selecciono Camisa Ingles ** Precio:$150 talla: 40";
        imagen = new ImageIcon("D:\\imgfotos\\albaca.PNG");
        productosSeleccionados.append("Calsado Albarca\n");
    }
    if (radio_Alpargata.isSelected()) {
        mensaje += "Selecciono Camisa Italiana ** Precio:$140  talla:35";
        imagen = new ImageIcon("D:\\imgfotos\\alpar.PNG");
        productosSeleccionados.append("Calsado Alpargata\n");
    }
    if (radio_Babucha.isSelected()) {
        mensaje += "Selecciono Camisa Cutaway ** Precio:$130 talla:39";
        imagen = new ImageIcon("D:\\imgfotos\\babu.PNG");
        productosSeleccionados.append("Casaca Babucha\n");
    }
    if (radio_Botas.isSelected()) {
        mensaje += "Selecciono Camisa Paloma ** Precio:$180 talla:37";
        imagen = new ImageIcon("D:\\imgfotos\\botas.PNG");
        productosSeleccionados.append("Calsado Botas\n");
    }

        label_concepto.setText(mensaje);
        label_icono.setIcon(imagen);
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_calsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_calsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_calsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_calsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_calsado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boton_agrupar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_atras;
    private javax.swing.JButton jbtn_comprar;
    private javax.swing.JButton jbtn_estadistica;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JLabel label_concepto;
    private javax.swing.JLabel label_icono;
    private javax.swing.JCheckBox radio_Albarca;
    private javax.swing.JCheckBox radio_Alpargata;
    private javax.swing.JCheckBox radio_Babucha;
    private javax.swing.JCheckBox radio_Botas;
    // End of variables declaration//GEN-END:variables
}
