
package jPack_Tienda_MarcoRath;
import jPack_Tienda_MarcoRath.jClass_Prendas_Vestir;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabel
 */
public class jFrame_Pantalones extends javax.swing.JFrame {
private jClass_Prendas_Vestir tiendaRopa;

 private int precioAcumulado = 0;
private StringBuilder productosSeleccionados = new StringBuilder();

    public jFrame_Pantalones() {
   this.tiendaRopa = new jClass_Prendas_Vestir(); // Crear una instancia de jClass_Prendas_Vestir y asignarla a this.tiendaRopa
    int precioJeans = tiendaRopa.getPrecioJeans();
    int precioJogger = tiendaRopa.getPrecioJogger();
    int precioChino = tiendaRopa.getPrecioChino();
    int precioLino = tiendaRopa.getPrecioLino();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_agrupar = new javax.swing.ButtonGroup();
        jbtn_aceptar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jbtn_atras = new javax.swing.JButton();
        jbtn_comprar = new javax.swing.JButton();
        label_icono = new javax.swing.JLabel();
        label_concepto = new javax.swing.JLabel();
        radio_jeans = new javax.swing.JCheckBox();
        radio_joger = new javax.swing.JCheckBox();
        radio_chino = new javax.swing.JCheckBox();
        radio_lino = new javax.swing.JCheckBox();
        jbtn_estadistica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 339, -1, -1));

        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 336, -1, -1));

        jbtn_atras.setText("Atras");
        jbtn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 377, -1, -1));

        jbtn_comprar.setText("Comprar");
        jbtn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 380, -1, -1));

        label_icono.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 59, 574, 259));

        label_concepto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 421, 362, 67));

        boton_agrupar.add(radio_jeans);
        radio_jeans.setText("Jeans");
        getContentPane().add(radio_jeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 21, -1, -1));

        boton_agrupar.add(radio_joger);
        radio_joger.setText("Jogger");
        getContentPane().add(radio_joger, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 21, -1, -1));

        boton_agrupar.add(radio_chino);
        radio_chino.setText("Chino");
        getContentPane().add(radio_chino, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 21, -1, -1));

        boton_agrupar.add(radio_lino);
        radio_lino.setText("Lino");
        getContentPane().add(radio_lino, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 21, -1, -1));

        jbtn_estadistica.setText("Estadistica");
        jbtn_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_estadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 336, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        String mensaje = ""; // Declarar la variable mensaje una vez antes de los bloques if
    ImageIcon imagen = null;

    // Preguntas qué botón se seleccionó
    if (radio_jeans.isSelected()) {
        mensaje += "Selecciono Pantalon Jean ** Precio:$150 Talla: X";
        imagen = new ImageIcon("D:\\imgfotos\\jhin.PNG");
        productosSeleccionados.append("Pantalon Jhin\n");
    }
    if (radio_joger.isSelected()) {
       mensaje += "Selecciono Pantalon Jogger ** Precio:$100 Talla: S";
        imagen = new ImageIcon("D:\\imgfotos\\joger.PNG");
          productosSeleccionados.append("Pantalon Jogger\n");
    }
    if (radio_chino.isSelected()) {
       mensaje += "Selecciono Pantalon Chino ** Precio:$80 Talla: M";
        imagen = new ImageIcon("D:\\imgfotos\\chino.PNG");
          productosSeleccionados.append("Pantalon Chino\n");
    }
    if (radio_lino.isSelected()) {
        mensaje += "Selecciono Pantalon Lino ** Precio:$110 Talla: XL";
        imagen = new ImageIcon("D:\\imgfotos\\lino.PNG");
          productosSeleccionados.append("Pantalon Lino\n");
    }

    label_concepto.setText(mensaje);
    label_icono.setIcon(imagen);
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    private void jbtn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_comprarActionPerformed
        int precioSeleccionado = 0;

    if (radio_jeans.isSelected()) {
        precioSeleccionado = tiendaRopa.getPrecioJeans();
    } else if (radio_joger.isSelected()) {
        precioSeleccionado = tiendaRopa.getPrecioJogger();
    } else if (radio_chino.isSelected()) {
        precioSeleccionado = tiendaRopa.getPrecioChino();
    } else if (radio_lino.isSelected()) {
        precioSeleccionado = tiendaRopa.getPrecioLino();
    }

    precioAcumulado += precioSeleccionado;

    String mensaje = "¡Has comprado un pantalón!\nPrecio Total: " + precioAcumulado;
    JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jbtn_comprarActionPerformed

    private void jbtn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasActionPerformed
       jFrame_Seleccion seleccion=new jFrame_Seleccion();
       seleccion.setVisible(true);
       dispose();
    }//GEN-LAST:event_jbtn_atrasActionPerformed

    private void jbtn_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_estadisticaActionPerformed
         String seleccionados = "";

    if (radio_jeans.isSelected()) {
        seleccionados += "Jeans\n";
    }
    if (radio_joger.isSelected()) {
        seleccionados += "Jogger\n";
    }
    if (radio_chino.isSelected()) {
        seleccionados += "Chino\n";
    }
    if (radio_lino.isSelected()) {
        seleccionados += "Lino\n";
    }

      String mensaje = "Elementos seleccionados:\n" + productosSeleccionados.toString() + "\nPrecio acumulado: " + precioAcumulado;
    JOptionPane.showMessageDialog(this, mensaje);


    }//GEN-LAST:event_jbtn_estadisticaActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
      radio_jeans.setSelected(false);
    radio_joger.setSelected(false);
    radio_chino.setSelected(false);
    radio_lino.setSelected(false);
    label_concepto.setText("");
    label_icono.setIcon(null);
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Pantalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Pantalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Pantalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Pantalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Pantalones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boton_agrupar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_atras;
    private javax.swing.JButton jbtn_comprar;
    private javax.swing.JButton jbtn_estadistica;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JLabel label_concepto;
    private javax.swing.JLabel label_icono;
    private javax.swing.JCheckBox radio_chino;
    private javax.swing.JCheckBox radio_jeans;
    private javax.swing.JCheckBox radio_joger;
    private javax.swing.JCheckBox radio_lino;
    // End of variables declaration//GEN-END:variables
}
