
package jPack_Tienda_MarcoRath;
import jPack_Tienda_MarcoRath.jClass_Prendas_Vestir;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class jFrame_Camisa extends javax.swing.JFrame {
private jClass_Prendas_Vestir tiendaRopa;
private StringBuilder productosSeleccionados = new StringBuilder();

 private int precioAcumulado = 0;
    public jFrame_Camisa() {
        initComponents();
    this.tiendaRopa = new jClass_Prendas_Vestir(); // Crear una instancia de jClass_Prendas_Vestir y asignarla a this.tiendaRopa
    int precioCamisaconcuelloInglés = tiendaRopa.getprecioCamisaconcuelloInglés();
    int precioCamisaconcuelloItaliano= tiendaRopa.getprecioCamisaconcuelloItaliano();
    int precioCamisaconcuelloCutaway = tiendaRopa.getprecioCamisaconcuelloCutaway();
    int precioCamisaconcuellopaloma = tiendaRopa.getprecioCamisaconcuellopaloma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_agrupar = new javax.swing.ButtonGroup();
        radio_ingles = new javax.swing.JCheckBox();
        radio_italiana = new javax.swing.JCheckBox();
        jbtn_aceptar = new javax.swing.JButton();
        radio_cutaway = new javax.swing.JCheckBox();
        jbtn_limpiar = new javax.swing.JButton();
        radio_paloma = new javax.swing.JCheckBox();
        jbtn_atras = new javax.swing.JButton();
        jbtn_estadistica = new javax.swing.JButton();
        jbtn_comprar = new javax.swing.JButton();
        label_concepto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_icono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_agrupar.add(radio_ingles);
        radio_ingles.setText("Ingles");
        getContentPane().add(radio_ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 21, -1, -1));

        boton_agrupar.add(radio_italiana);
        radio_italiana.setText("Italiana");
        getContentPane().add(radio_italiana, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 21, -1, -1));

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 349, -1, -1));

        boton_agrupar.add(radio_cutaway);
        radio_cutaway.setText("Kutaway");
        getContentPane().add(radio_cutaway, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 21, -1, -1));

        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 346, -1, -1));

        boton_agrupar.add(radio_paloma);
        radio_paloma.setText("Paloma");
        getContentPane().add(radio_paloma, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 21, -1, -1));

        jbtn_atras.setText("Atras");
        jbtn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 387, -1, -1));

        jbtn_estadistica.setText("Estadistica");
        jbtn_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_estadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 346, -1, -1));

        jbtn_comprar.setText("Comprar");
        jbtn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        label_concepto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(label_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 425, 368, 66));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        label_icono.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(label_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(label_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        String mensaje = ""; // Declarar la variable mensaje una vez antes de los bloques if
        ImageIcon imagen = null;

        // Preguntas qué botón se seleccionó
     if (radio_ingles.isSelected()) {
        mensaje += "Selecciono Camisa Ingles ** Precio:$70 Talla: X" ;
        imagen = new ImageIcon("D:\\imgfotos\\ingles.PNG");
        productosSeleccionados.append("Camisa Inglesa\n");
    }
    if (radio_italiana.isSelected()) {
        mensaje += "Selecciono Camisa Italiana ** Precio:$60 Talla: M";
        imagen = new ImageIcon("D:\\imgfotos\\italiana.PNG");
        productosSeleccionados.append("Camisa Italiana\n");
    }
    if (radio_cutaway.isSelected()) {
        mensaje += "Selecciono Camisa Cutaway ** Precio:$90 Talla: XL";
        imagen = new ImageIcon("D:\\imgfotos\\kutaway.PNG");
        productosSeleccionados.append("Camisa Cutaway\n");
    }
    if (radio_paloma.isSelected()) {
        mensaje += "Selecciono Camisa Paloma ** Precio:$75 Talla: S";
        imagen = new ImageIcon("D:\\imgfotos\\paloma.PNG");
        productosSeleccionados.append("Camisa Paloma\n");
    }

        label_concepto.setText(mensaje);
        label_icono.setIcon(imagen);
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
        radio_ingles.setSelected(false);
        radio_italiana.setSelected(false);
        radio_cutaway.setSelected(false);
        radio_paloma.setSelected(false);
        label_concepto.setText("");
        label_icono.setIcon(null);
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jbtn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasActionPerformed
        jFrame_Seleccion seleccion=new jFrame_Seleccion();
        seleccion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_atrasActionPerformed

    private void jbtn_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_estadisticaActionPerformed
        String seleccionados = "";

        if (radio_ingles.isSelected()) {
            seleccionados += "inglesa\n";
        }
        if (radio_italiana.isSelected()) {
            seleccionados += "italiana\n";
        }
        if (radio_cutaway.isSelected()) {
            seleccionados += "cutaway\n";
        }
        if (radio_paloma.isSelected()) {
            seleccionados += "paloma\n";
        }

        String mensaje = "Elementos seleccionados:\n" + productosSeleccionados.toString() + "\nPrecio acumulado: " + precioAcumulado;
    JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jbtn_estadisticaActionPerformed

    private void jbtn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_comprarActionPerformed
        int precioSeleccionado = 0;

        if (radio_ingles.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioCamisaconcuelloInglés();
        } else if (radio_italiana.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioCamisaconcuelloItaliano();
        } else if (radio_cutaway.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioCamisaconcuelloCutaway();
        } else if (radio_paloma.isSelected()) {
            precioSeleccionado = tiendaRopa.getprecioCamisaconcuellopaloma();
        }

        precioAcumulado += precioSeleccionado;

        String mensaje = "¡Has comprado un camiza!\nPrecio Total: " + precioAcumulado;
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jbtn_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Camisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Camisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Camisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Camisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Camisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boton_agrupar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_atras;
    private javax.swing.JButton jbtn_comprar;
    private javax.swing.JButton jbtn_estadistica;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JLabel label_concepto;
    private javax.swing.JLabel label_icono;
    private javax.swing.JCheckBox radio_cutaway;
    private javax.swing.JCheckBox radio_ingles;
    private javax.swing.JCheckBox radio_italiana;
    private javax.swing.JCheckBox radio_paloma;
    // End of variables declaration//GEN-END:variables
}
